const fs = require("fs");
const path = require("path");
const {
  withAndroidManifest,
  withAppBuildGradle,
  withDangerousMod,
  withGradleProperties,
  withMainApplication,
  AndroidConfig,
} = require("expo/config-plugins");

/**
 * Everything the engine needs, applied to the generated Android project.
 *
 * `android/` is generated by `expo prebuild` and is not committed, so none of
 * this can be a hand edit to a checked-in file - it would be gone the next time
 * anybody ran `--clean`. A config plugin is the version of that edit which
 * survives, and which applies the same way on a laptop as in CI instead of
 * living in one workflow's sed.
 *
 * Five separate things, each with its own reason:
 *
 *  1. The Kotlin sources and the resources they name.
 *  2. Registering the package, or the module is simply absent at runtime.
 *  3. The service, the receiver, and the loopback exception in the manifest.
 *  4. The packaging rules that let a 79 MB binary be EXECUTED rather than
 *     loaded, which is the whole reason this app can exist.
 *  5. One stable debug key, so a build installs over the previous one.
 */

const PACKAGE = "design.halleluja.arrowloop";

/** Copy the hand-written native sources into the generated project. */
function withNativeSources(config) {
  return withDangerousMod(config, [
    "android",
    (cfg) => {
      const root = cfg.modRequest.platformProjectRoot;
      const from = path.join(cfg.modRequest.projectRoot, "native");

      const java = path.join(root, "app", "src", "main", "java", ...PACKAGE.split("."));
      fs.mkdirSync(java, { recursive: true });
      const src = path.join(from, "java", ...PACKAGE.split("."));
      for (const file of fs.readdirSync(src)) {
        fs.copyFileSync(path.join(src, file), path.join(java, file));
      }

      // The resources EngineService names by R.*: the notification icon in
      // five densities and the channel's own strings. A missing drawable here
      // is not a build error - aapt resolves R.drawable.ic_notification only
      // if it exists - so this is the difference between a service that starts
      // and one that throws while putting up its notification.
      const res = path.join(root, "app", "src", "main", "res");
      copyTree(path.join(from, "res"), res);
      return cfg;
    },
  ]);
}

function copyTree(from, to) {
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const source = path.join(from, entry.name);
    const target = path.join(to, entry.name);
    if (entry.isDirectory()) {
      fs.mkdirSync(target, { recursive: true });
      copyTree(source, target);
    } else {
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.copyFileSync(source, target);
    }
  }
}

/** Register EnginePackage, without which the module does not exist at runtime. */
function withPackageRegistered(config) {
  return withMainApplication(config, (cfg) => {
    const marker = "add(EnginePackage())";
    if (cfg.modResults.contents.includes(marker)) return cfg;
    // Expo's template builds the list as `PackageList(this).packages.apply { }`
    // and the lambda is where a package that cannot be autolinked belongs.
    // Anchored on that exact construct rather than on a brace, so this cannot
    // land in whatever block happens to come first.
    cfg.modResults.contents = cfg.modResults.contents.replace(
      /(PackageList\(this\)\.packages\.apply\s*\{)/,
      `$1\n          ${marker}`,
    );
    if (!cfg.modResults.contents.includes(marker)) {
      throw new Error(
        "withEngine: could not find the package list in MainApplication - the Expo template changed shape, and a silently unregistered module is a NativeModules.ArrowLoopEngine that is simply undefined at runtime",
      );
    }
    return cfg;
  });
}

/** The service, the boot receiver, and cleartext to loopback only. */
function withEngineManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);

    app.service = app.service ?? [];
    if (!app.service.some((s) => s.$["android:name"] === ".EngineService")) {
      app.service.push({
        $: {
          "android:name": ".EngineService",
          "android:exported": "false",
          // dataSync is the honest type: this moves files between two places
          // on somebody's behalf. It carries the rules that come with it -
          // capped at six hours a day since Android 14, and timed out sooner
          // since 15. That is the budget the app lives inside, not a
          // limitation to work around.
          "android:foregroundServiceType": "dataSync",
        },
      });
    }

    // What Android calls when it is time. It needs the system's own permission
    // to be bindable as a job service, and WITHOUT that line Android silently
    // refuses to schedule anything: JobScheduler.schedule returns a failure
    // nobody reads, and the symptom is a phone that simply never syncs on its
    // own. Nothing in the app would say so.
    if (!app.service.some((s) => s.$["android:name"] === ".SyncJobService")) {
      app.service.push({
        $: {
          "android:name": ".SyncJobService",
          "android:exported": "false",
          "android:permission": "android.permission.BIND_JOB_SERVICE",
        },
      });
    }

    app.receiver = app.receiver ?? [];
    if (!app.receiver.some((r) => r.$["android:name"] === ".BootReceiver")) {
      app.receiver.push({
        $: { "android:name": ".BootReceiver", "android:exported": "true", "android:enabled": "true" },
        "intent-filter": [{ action: [{ $: { "android:name": "android.intent.action.BOOT_COMPLETED" } }] }],
      });
    }

    // usesCleartextTraffic is set by expo-build-properties and would permit
    // plain HTTP to ANY server. The network security config narrows it back to
    // the one address that needs it: the engine on 127.0.0.1.
    app.$["android:networkSecurityConfig"] = "@xml/network_security_config";
    return cfg;
  });
}

/** The loopback exception itself. */
function withNetworkConfig(config) {
  return withDangerousMod(config, [
    "android",
    (cfg) => {
      const dir = path.join(cfg.modRequest.platformProjectRoot, "app", "src", "main", "res", "xml");
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(
        path.join(dir, "network_security_config.xml"),
        `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withEngine.js - do not edit, android/ is thrown away.

     Plain HTTP to 127.0.0.1 and nowhere else. The engine serves its interface
     over loopback and has no certificate to present to itself; every other
     destination keeps the platform default, which is HTTPS or nothing. -->
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">127.0.0.1</domain>
        <domain includeSubdomains="false">localhost</domain>
    </domain-config>
    <base-config cleartextTrafficPermitted="false" />
</network-security-config>
`,
        "utf8",
      );
      return cfg;
    },
  ]);
}

/**
 * Packaging, ABI splits, and one stable debug key.
 *
 * `useLegacyPackaging` is the one that makes this app possible at all: the
 * engine has to arrive UNCOMPRESSED and stay a real file on disk, because it
 * is EXECUTED rather than loaded. Since Android 10 an app may not exec
 * anything out of its own data directory, and the one place left is the native
 * library directory - which is why a program ships as `libarrowloop.so`.
 *
 * The debug key is committed at android/debug.keystore in the repository root.
 * Without it Gradle signs with whatever debug keystore it finds in the
 * builder's home directory and creates one if there is none, so every CI build
 * carried a different key - and to Android a different signing key is a
 * different app. Every update refused with "signatures do not match".
 */
function withEngineGradle(config) {
  return withAppBuildGradle(config, (cfg) => {
    let gradle = cfg.modResults.contents;

    // ABI splits, one APK per architecture. The template has no splits block
    // at all, so this is an insertion rather than a replacement - anchored on
    // `defaultConfig {` because that is a construct every version of the
    // template has and `android {` alone would also match a comment.
    const SPLITS = "// arrowloop: one APK per architecture";
    if (!gradle.includes(SPLITS)) {
      gradle = gradle.replace(
        /(\n\s*defaultConfig\s*\{)/,
        `
    splits {
        abi {
            ${SPLITS}
            enable true
            reset()
            // arm64 is every phone sold in the last decade; x86_64 is what an
            // emulator is. armeabi-v7a is left out: the engine is 79 MB per
            // architecture and a 32-bit phone that can usefully sync a photo
            // library is not a real device any more. A universal APK would be
            // 158 MB of which every phone uses half.
            include "arm64-v8a", "x86_64"
            universalApk false
        }
    }
$1`,
      );
      if (!gradle.includes(SPLITS)) {
        throw new Error("withEngine: could not find defaultConfig to put the ABI splits before");
      }
    }

    // ONE debug key across the old shell and this app, which is the point of
    // pointing at the repository's rather than accepting the one the Expo
    // template ships. Both are stable - the template's is a fixed file in the
    // npm package, identical for everyone - but they are not the SAME key, and
    // to Android a different signing key is a different app. Using the shell's
    // key means the first build of this app installs OVER the shell rather
    // than demanding an uninstall that takes the settings with it.
    const KEY = "arrowloop/android/debug.keystore";
    if (!gradle.includes(KEY)) {
      const before = gradle;
      gradle = gradle.replace(
        /storeFile file\('debug\.keystore'\)/,
        // Relative to android/app: up to mobile/, up to the repository root.
        "storeFile file('../../../android/debug.keystore') // " + KEY,
      );
      if (gradle === before) {
        throw new Error("withEngine: could not find the debug signing config to repoint");
      }
    }

    cfg.modResults.contents = gradle;
    return cfg;
  });
}

/**
 * The engine has to arrive UNCOMPRESSED and stay a real file on disk, because
 * it is EXECUTED rather than loaded.
 *
 * Expo's template already reads this from a gradle property rather than
 * hard-coding it, so the honest way to set it is to set the property - not to
 * inject a second packagingOptions block that fights the first.
 */
function withLegacyPackaging(config) {
  return withGradleProperties(config, (cfg) => {
    const key = "expo.useLegacyPackaging";
    cfg.modResults = cfg.modResults.filter((item) => !("key" in item && item.key === key));
    cfg.modResults.push({
      type: "comment",
      value:
        " Set by plugins/withEngine.js. Since Android 10 an app may not execute a file out of its own data directory; the one place left is the native library directory, which is why the engine ships as libarrowloop.so - and it can only be executed there if it is not compressed.",
    });
    cfg.modResults.push({ type: "property", key, value: "true" });
    return cfg;
  });
}

module.exports = function withEngine(config) {
  config = withNativeSources(config);
  config = withPackageRegistered(config);
  config = withEngineManifest(config);
  config = withNetworkConfig(config);
  config = withEngineGradle(config);
  config = withLegacyPackaging(config);
  return config;
};
