// Every language, bundled.
//
// The web app fetches these one chunk at a time, because forty-one languages
// nobody is reading have no business in a page load. A phone is the opposite
// case: the download happened once at install, and a translation that has to
// be fetched is one that is missing on a train. So all of them are in here.
//
// Generated by tools/make_locales.py from web/src/lib/locales - the SAME files
// the container serves, so the two can never disagree about a sentence.

import type { Translations } from "../../web/src/lib/i18n.data";

import ar from "../../web/src/lib/locales/ar";
import bg from "../../web/src/lib/locales/bg";
import ca from "../../web/src/lib/locales/ca";
import cs from "../../web/src/lib/locales/cs";
import da from "../../web/src/lib/locales/da";
import el from "../../web/src/lib/locales/el";
import es from "../../web/src/lib/locales/es";
import et from "../../web/src/lib/locales/et";
import eu from "../../web/src/lib/locales/eu";
import fa from "../../web/src/lib/locales/fa";
import fi from "../../web/src/lib/locales/fi";
import fr from "../../web/src/lib/locales/fr";
import gl from "../../web/src/lib/locales/gl";
import he from "../../web/src/lib/locales/he";
import hi from "../../web/src/lib/locales/hi";
import hr from "../../web/src/lib/locales/hr";
import hu from "../../web/src/lib/locales/hu";
import id from "../../web/src/lib/locales/id";
import is from "../../web/src/lib/locales/is";
import it from "../../web/src/lib/locales/it";
import ja from "../../web/src/lib/locales/ja";
import ko from "../../web/src/lib/locales/ko";
import lt from "../../web/src/lib/locales/lt";
import lv from "../../web/src/lib/locales/lv";
import ms from "../../web/src/lib/locales/ms";
import nl from "../../web/src/lib/locales/nl";
import no from "../../web/src/lib/locales/no";
import pl from "../../web/src/lib/locales/pl";
import pt from "../../web/src/lib/locales/pt";
import ro from "../../web/src/lib/locales/ro";
import ru from "../../web/src/lib/locales/ru";
import sk from "../../web/src/lib/locales/sk";
import sl from "../../web/src/lib/locales/sl";
import sr from "../../web/src/lib/locales/sr";
import sv from "../../web/src/lib/locales/sv";
import th from "../../web/src/lib/locales/th";
import tr from "../../web/src/lib/locales/tr";
import uk from "../../web/src/lib/locales/uk";
import vi from "../../web/src/lib/locales/vi";
import zh from "../../web/src/lib/locales/zh";

export const locales: Record<string, Partial<Translations>> = {
  "ar": ar as Partial<Translations>,
  "bg": bg as Partial<Translations>,
  "ca": ca as Partial<Translations>,
  "cs": cs as Partial<Translations>,
  "da": da as Partial<Translations>,
  "el": el as Partial<Translations>,
  "es": es as Partial<Translations>,
  "et": et as Partial<Translations>,
  "eu": eu as Partial<Translations>,
  "fa": fa as Partial<Translations>,
  "fi": fi as Partial<Translations>,
  "fr": fr as Partial<Translations>,
  "gl": gl as Partial<Translations>,
  "he": he as Partial<Translations>,
  "hi": hi as Partial<Translations>,
  "hr": hr as Partial<Translations>,
  "hu": hu as Partial<Translations>,
  "id": id as Partial<Translations>,
  "is": is as Partial<Translations>,
  "it": it as Partial<Translations>,
  "ja": ja as Partial<Translations>,
  "ko": ko as Partial<Translations>,
  "lt": lt as Partial<Translations>,
  "lv": lv as Partial<Translations>,
  "ms": ms as Partial<Translations>,
  "nl": nl as Partial<Translations>,
  "no": no as Partial<Translations>,
  "pl": pl as Partial<Translations>,
  "pt": pt as Partial<Translations>,
  "ro": ro as Partial<Translations>,
  "ru": ru as Partial<Translations>,
  "sk": sk as Partial<Translations>,
  "sl": sl as Partial<Translations>,
  "sr": sr as Partial<Translations>,
  "sv": sv as Partial<Translations>,
  "th": th as Partial<Translations>,
  "tr": tr as Partial<Translations>,
  "uk": uk as Partial<Translations>,
  "vi": vi as Partial<Translations>,
  "zh": zh as Partial<Translations>,
};
