"""Generate the provider marks from Simple Icons.

    npm install simple-icons@16 somewhere, then:
    python scripts/gen_brand_glyphs.py <path to simple-icons/icons>

Simple Icons is CC0, so a mark taken from it carries no attribution duty. The
trademarks remain their owners': every mark here only names the service it
belongs to, on a row that connects to exactly that service, reproduced
unmodified apart from its colour, with no claim of endorsement or affiliation.

Writes web/src/components/brandGlyphs.tsx whole, including the GitHub mark, and
web/src/brandGlyphs.css.
"""
import colorsys
import io
import json
import os
import re
import sys
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path

# Measures where a mark actually paints, which needs transforms and bezier
# bounds resolved. The import is soft so the failure names the package.
try:
    import svgelements
except ImportError:  # pragma: no cover
    svgelements = None

SRC = Path(sys.argv[1] if len(sys.argv) > 1 else
           "C:/Users/JUNKER~1/AppData/Local/Temp/si/node_modules/simple-icons/icons")
OUT = Path(__file__).parent.parent / "web" / "src" / "components" / "brandGlyphs.tsx"

# Our component name -> the Simple Icons slug, with what it is for.
#
# A mark naming the right company but not the exact product is better than
# none; a mark naming a different product is not, and such a provider shows a
# generic glyph instead.
MARKS = [
    ("IconGithub", "github", "This project's own repository"),

    # OpenCloud never wears ownCloud's mark; its own drawing is under LOCAL.
    ("IconNextcloud", "nextcloud", "Nextcloud"),
    ("IconOwncloud", "owncloud", "ownCloud"),

    ("IconDropbox", "dropbox", "Dropbox"),
    ("IconGooglePhotos", "googlephotos", "Google Photos"),
    ("IconGoogleCloud", "googlecloud", "Google Cloud Storage"),
    ("IconBox", "box", "Box"),
    ("IconMailru", "maildotru", "Mail.ru Cloud"),
    ("IconZoho", "zoho", "Zoho WorkDrive"),
    ("IconSeafile", "seafile", "Seafile"),
    # ShareFile was Citrix's and the mark is still filed under the parent.
    ("IconCitrix", "citrix", "ShareFile, filed under Citrix"),

    # Object storage and infrastructure.
    ("IconBackblaze", "backblaze", "Backblaze B2"),
    ("IconOpenstack", "openstack", "OpenStack Swift"),
    ("IconAkamai", "akamai", "Akamai NetStorage"),
    ("IconHadoop", "apachehadoop", "HDFS"),

    # S3-compatible presets. IDrive, Linode and SeaweedFS have no mark in this
    # set; theirs are under LOCAL.
    ("IconWasabi", "wasabi", "Wasabi"),
    ("IconCloudflare", "cloudflare", "Cloudflare R2"),
    ("IconDigitalOcean", "digitalocean", "DigitalOcean Spaces"),
    ("IconScaleway", "scaleway", "Scaleway Object Storage"),
    ("IconHetzner", "hetzner", "Hetzner Object Storage"),
    ("IconOvh", "ovh", "OVHcloud Object Storage"),
    ("IconSynology", "synology", "Synology C2"),
    ("IconMinio", "minio", "MinIO"),
]

HEAD = '''import type { SVGProps } from 'react'

// Brand marks. GENERATED by scripts/gen_brand_glyphs.py, do not hand-edit.
//
// Kept apart from `glyphs.tsx`, which is one icon set drawn to one convention.
// A brand mark is somebody else's drawing: it is not redrawn to fit, and a
// provider without its own mark gets none rather than a neighbour's.
//
// Sources: Simple Icons (simpleicons.org, CC0), and brand files recorded per
// mark below.
//
// Trademarks: every mark belongs to its owner and is used only to name the
// service it refers to, on a row that connects to exactly that service,
// reproduced unmodified apart from its colour, with no claim of endorsement by
// or affiliation with any of them. A brand mark is never reached by pattern from
// a translation key; it is passed at the call site that means it.

'''


# Marks drawn in their brand colours vanish on one of the grounds: navy or black
# on the dark theme, near-white on the light one. A mark that cannot be read on
# one ground gets a variant for that ground only, same hue and saturation with
# its lightness moved until it can be seen. Which marks need it is measured from
# the colours rather than kept as a list of names.
SURFACE_DARK = "#393939"   # --carbon-surface2, dark theme: what a row is filled with
SURFACE_LIGHT = "#e8e8e8"  # --carbon-surface2, light theme

# A shifted light value lands on three grounds: the white card, a tile's own
# #e8e8e8 and the light theme's row hover at #d1d1d1.
GROUNDS_LIGHT = ("#ffffff", SURFACE_LIGHT, "#d1d1d1")

# Below this contrast a mark is not readable against a ground: Dropbox's blue at
# 2.28 reads well, Filen's black at 1.90 does not.
FLOOR = 2.0
# The light theme keeps a brand's own colour down to this ("Brand tiles" in
# GlimStone): an orange still reads as orange on light grey, because the hue does
# the recognising, and only white and near-white parts vanish.
LIGHT_FLOOR = 1.35
# What a flipped colour has to reach: the text threshold rather than the 3.0 for
# graphics, since a mark this small is closer to a letterform.
TARGET = 4.5


# Colour keywords found in these files (put.io writes `fill="white"`). Any other
# keyword is refused below, since the readability check could not measure it.
KEYWORDS = {"white": "#ffffff", "black": "#000000"}


def _rgb(colour):
    """`#a00`, `#aa0000`, `rgb(170, 0, 0)` or a known keyword, as 0-255."""
    text = KEYWORDS.get(colour.strip().lower(), colour).strip()
    if text.startswith("rgb"):
        parts = re.findall(r"[\d.]+%?", text)[:3]
        if len(parts) < 3:
            return None
        # Cairo exports write `rgb(28.2%,58%,99.6%)`; read as 0-255 that bright
        # blue would become navy.
        return tuple(
            int(round(float(p[:-1]) * 255 / 100)) if p.endswith("%") else int(float(p))
            for p in parts
        )
    text = text.lstrip("#")
    if len(text) == 3:
        text = "".join(c * 2 for c in text)
    if len(text) != 6:
        return None
    return tuple(int(text[i:i + 2], 16) for i in (0, 2, 4))


def _luminance(rgb):
    def channel(value):
        value /= 255.0
        return value / 12.92 if value <= 0.03928 else ((value + 0.055) / 1.055) ** 2.4
    r, g, b = (channel(v) for v in rgb)
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(one_colour, other):
    a, b = sorted((_luminance(_rgb(one_colour)), _luminance(_rgb(other))), reverse=True)
    return (a + 0.05) / (b + 0.05)


def on_light_grounds(colour):
    """The worst contrast this colour reaches on any light ground it can land
    on. A near-white colour is worst against white, a dark one against
    #d1d1d1."""
    return min(contrast(colour, ground) for ground in GROUNDS_LIGHT)


def shift(colour, surface, upward, also=()):
    """The same colour, moved along lightness until it can be seen.

    Hue and saturation are untouched; black and white have no hue and become
    their opposite end. `also` names further (ground, minimum) pairs the result
    must satisfy on top of reaching TARGET on `surface`, since a colour tuned
    against the resting #e8e8e8 can still fall under the floor on the hovered
    #d1d1d1.
    """
    rgb = _rgb(colour)
    hue, light, sat = colorsys.rgb_to_hls(*(v / 255.0 for v in rgb))
    step = 0.02 if upward else -0.02
    limit = 0.94 if upward else 0.10
    while (light < limit) if upward else (light > limit):
        light += step
        candidate = "#%02x%02x%02x" % tuple(
            round(v * 255) for v in colorsys.hls_to_rgb(hue, min(max(light, 0.0), 1.0), sat)
        )
        if contrast(candidate, surface) >= TARGET and all(
            contrast(candidate, ground) >= minimum for ground, minimum in also
        ):
            return candidate
    return "#%02x%02x%02x" % tuple(
        round(v * 255) for v in colorsys.hls_to_rgb(hue, min(max(light, 0.0), 1.0), sat)
    )


# Every custom property the marks need, in the order they were minted, as
# (name, value on dark, value on light).
VARIABLES = []

# Colours that follow the theme even though the mark as a whole reads fine.
#
# The readability rule judges a mark by its best colour. Most white in a logo is
# a knockout on the brand's own shape (MEGA's M on its red circle) and must stay
# white; white sitting directly on the page vanishes on the light theme, and no
# measurement here can tell the two apart. Values are (on dark, on light).
FORCE_THEMED = {
    # Drawn for the near-black plate _drop_plate removes; on the light theme the
    # white bars take the plate's tone.
    "opendrive": {"#fff": ("#ffffff", "#2b2b2b")},
    # White on a #3d3d3d plate, likewise.
    "ulozto": {"#fff": ("#ffffff", "#3d3d3d")},
}


def _drop_plate(root, source, slug):
    """Remove the rectangle the rest of the mark is sitting on.

    A brand asset is often drawn on a plate, which in a list of logos makes it
    the one mark arriving in its own box. A plate is the first thing drawn, a
    rectangle, with everything else inside it; it need not fill the canvas
    (Linkbox's plate covers a fifth of a 367x70 canvas whose text was lost on
    export). A white mark left invisible on a light page is handled by
    FORCE_THEMED. Returns the plate's colour, which a mark painting only white
    lights its tile up in.
    """
    if svgelements is None:
        raise SystemExit("the plate rule needs svgelements (pip install svgelements)")
    try:
        drawing = svgelements.SVG.parse(str(source))
    except Exception:
        return

    boxes = []
    for element in drawing.elements():
        if not isinstance(element, svgelements.Shape):
            continue
        try:
            bounds = element.bbox()
        except Exception:
            continue
        if bounds:
            boxes.append((type(element).__name__, bounds))
    if len(boxes) < 2 or boxes[0][0] != "Rect":
        return

    plate = boxes[0][1]
    rest = boxes[1:]
    # Half a unit of tolerance for drawing-program rounding.
    covers = (
        plate[0] <= min(b[0] for _, b in rest) + 0.5
        and plate[1] <= min(b[1] for _, b in rest) + 0.5
        and plate[2] >= max(b[2] for _, b in rest) - 0.5
        and plate[3] >= max(b[3] for _, b in rest) - 0.5
    )
    if not covers:
        return

    parents = {child: parent for parent in root.iter() for child in parent}
    for el in root.iter():
        if el.tag == SVG_NS + "rect":
            parents[el].remove(el)
            print("  %s: dropped the plate it was sitting on (%gx%g)"
                  % (slug, plate[2] - plate[0], plate[3] - plate[1]))
            return _declared(el, "fill")


def themed(colours, slug, ground=None):
    """Which of these colours need a per-theme variant, and under what names.

    Returns a map from the colour as written in the file to the `var(...)` that
    replaces it, empty when the mark reads fine on both grounds. The dark theme
    is judged per mark, so a two-tone logo is not half flipped. The light theme
    is judged per colour, and only for the colours in `ground` (as 0-255
    triples), the ones painting straight onto the page somewhere in the mark: a
    white that lies on another part, like the eyes on PikPak's face, is seen
    against that part. None counts every colour.
    """
    usable = [c for c in colours if _rgb(c)]
    if not usable:
        return {}

    forced = {}
    for colour, (on_dark, on_light) in FORCE_THEMED.get(slug, {}).items():
        if colour not in usable:
            raise SystemExit("FORCE_THEMED names %s in %s, which does not paint with it" % (colour, slug))
        # A hand-picked pair is measured too.
        if contrast(on_dark, SURFACE_DARK) < FLOOR or on_light_grounds(on_light) < FLOOR:
            raise SystemExit(
                "FORCE_THEMED %s/%s is too faint: %.2f on the dark ground, %.2f on the "
                "worst light one" % (slug, colour, contrast(on_dark, SURFACE_DARK),
                                     on_light_grounds(on_light))
            )
        name = "--brand-%s-forced%d" % (slug, len(forced))
        VARIABLES.append((name, _hex(on_dark), _hex(on_light)))
        forced[colour] = "var(%s)" % name

    # A forced colour settles that colour, not the mark; the rest is measured.
    rest = [c for c in usable if c not in forced]
    if not rest:
        return forced

    lift = max(contrast(c, SURFACE_DARK) for c in rest) < FLOOR
    fade = {
        _rgb(c) for c in rest
        if (ground is None or _rgb(c) in ground) and contrast(c, SURFACE_LIGHT) < LIGHT_FLOOR
    }
    if not lift and not fade:
        return forced
    if lift and len(fade) == len({_rgb(c) for c in rest}):
        raise SystemExit(
            "%s cannot be read on either ground: it needs a different source file, "
            "not a lightness shift" % slug
        )
    swap = dict(forced)
    minted = {}
    for colour in rest:
        # Keyed by value, since one file writes `#20434F` and `#20434f`.
        key = _rgb(colour)
        if key not in minted:
            on_dark = shift(colour, SURFACE_DARK, upward=True) if lift else colour
            on_light = (
                shift(colour, SURFACE_LIGHT, upward=False,
                      also=[(g, FLOOR) for g in GROUNDS_LIGHT])
                if key in fade
                else colour
            )
            if on_dark == colour and on_light == colour:
                minted[key] = None
            else:
                name = "--brand-%s-%d" % (slug, sum(1 for v in minted.values() if v))
                VARIABLES.append((name, _hex(on_dark), _hex(on_light)))
                minted[key] = name
        if minted[key]:
            swap[colour] = "var(%s)" % minted[key]
    return swap


def _hex(colour):
    """A colour as a hex string, whatever it was written as, because
    brandContrast.test.ts reads the emitted CSS and parses hex only."""
    text = KEYWORDS.get(str(colour).strip().lower())
    return text or colour


def apply_swap(source, swap):
    """Put the custom properties where the literal colours were, except inside
    a `<mask>`, where white means "show all of this" and a theme variable would
    make the logo fade rather than flip."""
    masks = []

    def park(match):
        masks.append(match.group(0))
        return "\0mask%d\0" % (len(masks) - 1)

    source = re.sub(r"<mask\b.*?</mask>", park, source, flags=re.S)
    for colour, variable in swap.items():
        source = source.replace('"%s"' % colour, '"%s"' % variable)
        # The fallback inside a hover role, `var(--mark-ink, #fff)`.
        source = source.replace(", %s)" % colour, ", %s)" % variable)
    for index, block in enumerate(masks):
        source = source.replace("\0mask%d\0" % index, block)
    return source


# What each mark's tile lights up in under the pointer, as (tile colour, ink),
# by component name, written to brandGlyphs.tsx as BRAND_TILES.
TILES = {}

# Brands whose tile colour the mark does not say: the largest area misses it
# (Huawei's gradient, OneDrive's blues), or the brand pairs its mark with an ink
# of its own (OpenCloud's lavender on petrol). None takes the measured ink.
TILE_COLOUR = {
    "huaweicloud": ("#c7000b", None),
    "microsoft-onedrive": ("#0078d4", None),
    "protondrive": ("#6d4aff", None),
    # SeaweedFS blue rather than the pale cyan it covers most with, so its
    # bubbles stay white.
    "seaweedfs": ("#0162bf", None),
    "opencloud": ("#20434f", "#e2baff"),
}


def tile(name, slug, colour):
    """Record the colour a mark's tile lights up in, and the ink on it: white
    wherever white reaches 2:1, near-black below that."""
    colour, ink = TILE_COLOUR.get(slug, (colour, None))
    if not colour:
        raise SystemExit("%s paints no colour its tile could take; add it to TILE_COLOUR" % slug)
    colour = _hex(colour).lower()
    if len(colour) == 4:
        colour = "#" + "".join(c * 2 for c in colour[1:])
    TILES[name] = (colour, ink or ("#ffffff" if contrast(colour, "#ffffff") >= 2 else "#161616"))


# Marks whose layers do not survive one ink, lit with the brand's own
# single-colour mark from Simple Icons instead: Proton Drive's two folders in
# overlapping gradients come out as a fragment.
HOVER = {"IconProtonDrive": "protondrive"}


# The brands' own colours, keyed by slug, from the set's own data file.
COLOURS = {}
_data = SRC.parent / "data" / "simple-icons.json"
if _data.exists():
    _raw = json.loads(io.open(_data, encoding="utf-8").read())
    for entry in (_raw["icons"] if isinstance(_raw, dict) else _raw):
        title = entry.get("title", "")
        # The set's own rule: the title lowercased with everything but letters
        # and digits removed, unless a `slug` field says otherwise.
        s_ = entry.get("slug") or re.sub(r"[^a-z0-9]", "", title.lower())
        COLOURS[s_] = "#" + entry["hex"]


def one(name: str, slug: str, note: str) -> str:
    svg = io.open(SRC / (slug + ".svg"), encoding="utf-8").read()
    box = re.search(r'viewBox="([^"]+)"', svg)
    paths = re.findall(r'<path d="([^"]+)"', svg)
    if not box or not paths:
        raise SystemExit("cannot read %s.svg" % slug)
    colour = COLOURS.get(slug)
    if not colour:
        raise SystemExit("no brand colour for %s: the data file did not carry it" % slug)
    body = "\n".join('      <path d="%s" />' % d for d in paths)
    # The brand's own colour rather than currentColor, which would make a
    # silhouette of the logo. Simple Icons draws each mark in one colour, the
    # primary one for a multi-coloured brand. `fill` sits on the svg so one style
    # can still override the whole mark.
    swap = themed([colour], slug)
    painted = swap.get(colour, colour)
    aside = "" if not swap else ", flipped for the ground it cannot be read on"
    tile(name, slug, colour)
    # crop_to_ink tightens the box later, off the finished markup.
    cropped = box.group(1)
    return f'''/** {note}. Simple Icons: {slug}, in its own {colour}{aside} */
export function {name}(props: SVGProps<SVGSVGElement>) {{
  return (
    <svg viewBox="{cropped}" width="1em" height="1em" fill="var(--mark-ink, {painted})" aria-hidden {{...props}}>
{body}
    </svg>
  )
}}
'''


# Brands' own drawings kept as SVG under scripts/brand-paths/, reproduced
# unmodified, with source and licence recorded here and in that folder's README.
# The trademark use is the same as above.
#
# A `-dark`/`-light` pair is one drawing in two inks: `-dark` for a light ground,
# `-light` for a dark one. Where a pair exists it replaces the computed
# lightness shift.
JDP = "supplied by jdp, from the brand's own material"
BRAND = "the brand's own mark"

LOCAL = [
    ("IconPcloud", "pcloud", "pCloud", JDP, BRAND),
    ("IconKoofr", "koofr", "Koofr", JDP, BRAND),
    ("IconJottacloud", "jottacloud", "Jottacloud", JDP, BRAND),
    ("IconOpendrive", "opendrive", "OpenDrive", JDP, BRAND),
    ("IconPutio", "putio", "put.io", JDP, BRAND),
    ("IconSugarsync", "sugarsync", "SugarSync", JDP, BRAND),
    ("IconPikpak", "pikpak", "PikPak", JDP, BRAND),
    ("IconInternxt", "internxt", "Internxt", JDP, BRAND),
    ("IconUlozto", "ulozto", "Ulož.to", JDP, BRAND),

    # Linode and IDrive from the dashboard-icons set (Apache 2.0), SeaweedFS from
    # the project's own repository.
    ("IconLinode", "linode", "Linode Object Storage", JDP, BRAND),
    ("IconIdrive", "idrive", "IDrive e2", JDP, BRAND),
    ("IconSeaweedfs", "seaweedfs", "SeaweedFS", JDP, BRAND),

    ("IconCeph", "ceph", "Ceph", JDP, BRAND),
    ("IconGarage", "garage", "Garage",
     "the Garage project's own icon, via junkerderprovinz/garage", BRAND),
    ("IconQuatrix", "quatrix", "Quatrix", JDP, BRAND),
    ("IconLinkbox", "linkbox", "Linkbox", JDP, BRAND),
    ("IconGofile", "gofile", "Gofile", JDP, BRAND),
    ("IconPixeldrain", "pixeldrain", "Pixeldrain", JDP, BRAND),

    ("IconAzure", "azureblob", "Azure Blob Storage, under Azure's own mark", JDP, BRAND),
    ("IconFilen", "filen", "Filen", JDP, BRAND),
    ("IconFilesCom", "filescom", "Files.com", JDP, BRAND),
    ("IconGoogleDrive", "gdrive", "Google Drive", JDP, BRAND),
    ("IconHuaweiCloud", "huaweicloud", "Huawei Cloud OBS", JDP, BRAND),
    ("IconICloud", "icloud", "iCloud Drive", JDP, BRAND),
    ("IconIonos", "hidrive", "IONOS HiDrive", JDP, BRAND),
    ("IconMega", "mega", "MEGA", JDP, BRAND),
    ("IconProtonDrive", "protondrive", "Proton Drive", JDP, BRAND),
    ("IconStorj", "storj", "Storj", JDP, BRAND),
    ("IconYandex", "yandex", "Yandex Disk, under Yandex Cloud's mark", JDP, BRAND),

    # Pairs: one drawing, two inks, picked by theme.
    ("IconCloudinary", "cloudinary", "Cloudinary", JDP, BRAND),
    ("IconInternetArchive", "internetarchive", "Internet Archive", JDP, BRAND),
    ("IconOpencloud", "opencloud", "OpenCloud", JDP, BRAND),

    # Dashboard Icons, Apache-2.0.
    ("IconOnedrive", "microsoft-onedrive", "OneDrive",
     "homarr-labs/dashboard-icons, svg/microsoft-onedrive.svg", "Apache-2.0"),
    ("IconOracleCloud", "oracle-cloud", "Oracle Object Storage, part of Oracle Cloud",
     "homarr-labs/dashboard-icons, svg/oracle-cloud.svg", "Apache-2.0"),
]

# Attributes that mean nothing inside a component, or that the wrapper sets.
DROP_ROOT = {"xmlns", "version", "width", "height", "id", "class"}

# SVG attribute -> its JSX spelling, where lowercasing the hyphen is not the
# rule. Everything else hyphenated is camelCased below.
SPECIAL = {"class": "className", "for": "htmlFor"}


def _camel(name):
    """`stop-color` -> `stopColor`, but `data-x` and `aria-x` stay put."""
    if name.startswith("data-") or name.startswith("aria-"):
        return name
    if name in SPECIAL:
        return SPECIAL[name]
    head, _, tail = name.partition("-")
    while tail:
        piece, _, rest = tail.partition("-")
        head += piece[:1].upper() + piece[1:]
        tail = rest
    return head


def _style_object(value):
    """`fill:#a00;fill-opacity:1` -> a JSX style object, which JSX takes in
    place of the CSS string an SVG file carries."""
    pairs = []
    for chunk in value.split(";"):
        key, sep, val = chunk.partition(":")
        if not sep or not key.strip():
            continue
        pairs.append("%s: %s" % (_camel(key.strip()), json.dumps(val.strip())))
    return "{{ %s }}" % ", ".join(pairs) if pairs else None


def _jsx(node, ids, slug, depth):
    """One SVG element and its children as JSX source, or None to skip it."""
    tag = node.tag.split("}")[-1]
    # They hold the designer's asset name ("Icon-storage-86"), and the wrapper is
    # aria-hidden with the provider's name beside it.
    if tag in ("title", "desc"):
        return None
    pad = "  " * depth
    attrs = []
    for raw, value in node.attrib.items():
        # `xlink:href` arrives fully qualified and is `xlinkHref` in JSX.
        if raw.startswith("{http://www.w3.org/1999/xlink}"):
            key = "xlinkHref"
        elif raw.startswith("{"):
            continue  # any other foreign namespace means nothing to the DOM here
        else:
            key = _camel(raw)
        if key in ("xmlns", "xmlnsXlink", "version"):
            continue
        # Ids are prefixed with the slug, since `url(#radial0)` resolves to the
        # first match in the document and one logo would wear another's
        # gradient.
        if key == "id":
            value = ids[value]
        else:
            for old, new in ids.items():
                value = value.replace("url(#%s)" % old, "url(#%s)" % new)
                if value == "#" + old:
                    value = "#" + new
        if key == "style":
            obj = _style_object(value)
            if not obj:
                continue
            attrs.append("style=%s" % obj)
            continue
        attrs.append("%s=%s" % (key, '"%s"' % value if '"' not in value else "{%s}" % json.dumps(value)))
    head = ("<%s " % tag) + " ".join(attrs) if attrs else "<%s" % tag
    # Text would otherwise be dropped silently; a mark drawing with <text> stops
    # the build rather than losing its lettering.
    if (node.text or "").strip():
        raise SystemExit("brand-paths/%s.svg: <%s> carries text this generator drops" % (slug, tag))

    kids = [c for c in (_jsx(k, ids, slug, depth + 1) for k in node) if c]
    if not kids:
        return "%s%s />" % (pad, head)
    return "%s%s>\n%s\n%s</%s>" % (pad, head, "\n".join(kids), pad, tag)


BRAND_DIR = Path(__file__).parent / "brand-paths"

SVG_NS = "{http://www.w3.org/2000/svg}"
# So a mark written back out for measuring keeps its plain tag names.
ET.register_namespace("", "http://www.w3.org/2000/svg")
ET.register_namespace("xlink", "http://www.w3.org/1999/xlink")

# Hand-set viewBoxes for a mark crop_to_ink measures wrongly, by component name.
# An entry that only restates the measurement is refused.
INK = {}

# How much of its box a mark may waste before it is cropped: above the rounding
# in these files and below what the eye resolves.
SLACK = 1.02

# Redundant INK entries, refused together at the end of the run.
REDUNDANT = []


def _measure_ink(component, name):
    """The box the mark actually paints in, in its own viewBox units.

    Measured off the finished markup, after the plate is dropped, the styles
    folded in and the ids prefixed. `<defs>`, `<mask>` and `<clipPath>` are cut
    out first, since a full-canvas mask rectangle (Quatrix has two) would report
    the whole box as painted.
    """
    if svgelements is None:
        raise SystemExit(
            "crop_to_ink needs the svgelements package (pip install svgelements).\n"
            "It measures where each mark actually paints."
        )
    markup = component[component.index("<svg"):component.rindex("</svg>") + 6]
    markup = markup.replace(" aria-hidden {...props}", " ").replace("{...props}", " ")

    # JSX spellings back to SVG's own, for the attributes these files carry.
    def style(match):
        pairs = re.findall(r'(\w+):\s*"([^"]*)"', match.group(1))
        return 'style="%s"' % ";".join(
            "%s:%s" % (re.sub(r"(?<!^)(?=[A-Z])", "-", key).lower(), value)
            for key, value in pairs
        )

    markup = re.sub(r"style=\{\{([^}]*)\}\}", style, markup)
    for jsx, svg in (
        ("fillRule", "fill-rule"), ("fillOpacity", "fill-opacity"),
        ("clipPath", "clip-path"), ("clipRule", "clip-rule"),
        ("strokeWidth", "stroke-width"), ("strokeLinecap", "stroke-linecap"),
        ("strokeLinejoin", "stroke-linejoin"), ("strokeMiterlimit", "stroke-miterlimit"),
        ("stopColor", "stop-color"), ("stopOpacity", "stop-opacity"),
        ("xlinkHref", "xlink:href"), ("fillOpacity", "fill-opacity"),
    ):
        markup = markup.replace(jsx + "=", svg + "=")
    for tag in ("defs", "mask", "clipPath"):
        markup = re.sub(r"<%s\b.*?</%s>" % (tag, tag), "", markup, flags=re.S)

    box = [float(v) for v in re.search(r'viewBox="([^"]+)"', markup).group(1).replace(",", " ").split()]
    # The parser cannot resolve `width="1em"`. The viewBox's own size makes the
    # viewport transform the identity, so the results are in viewBox units.
    markup = re.sub(r'\swidth="[^"]*"', "", markup, count=1)
    markup = re.sub(r'\sheight="[^"]*"', "", markup, count=1)
    markup = markup.replace(
        "<svg ",
        '<svg xmlns="http://www.w3.org/2000/svg" width="%g" height="%g" ' % (box[2], box[3]),
        1,
    )

    handle, path = tempfile.mkstemp(suffix=".svg")
    os.close(handle)
    try:
        io.open(path, "w", encoding="utf-8").write(markup)
        drawing = svgelements.SVG.parse(path)
    finally:
        os.unlink(path)

    left = top = float("inf")
    right = bottom = float("-inf")
    for element in drawing.elements():
        if not isinstance(element, svgelements.Shape):
            continue
        try:
            # With the stroke, since a mark drawn as an outline (Oracle Cloud's
            # 4-unit stroke) would otherwise lose half of it at every edge.
            bounds = element.bbox(with_stroke=True)
        except Exception:
            continue
        if not bounds:
            continue
        left, top = min(left, bounds[0]), min(top, bounds[1])
        right, bottom = max(right, bounds[2]), max(bottom, bounds[3])
    if right <= left or bottom <= top:
        raise SystemExit("%s paints nothing this can measure" % name)
    # Back into the box's own coordinates: the parse put its origin at 0,0.
    return box, (left + box[0], top + box[1], right - left, bottom - top)


# What a lit tile does with a mark ("Brand tiles" in GlimStone): every part
# turns the tile's ink, except a part lying on a part of another colour, which
# becomes a cut-out in the tile colour, like the M on MEGA's disc or the eyes on
# PikPak's face. A part at most this far from the colour under it is the same
# surface drawn twice, not a detail on it (Euclidean distance in 0-255 RGB).
SAME_SURFACE = 60
# How much of a part's box has to lie on another part for it to count as lying
# on it. Boxes, not shapes, so the margin covers a round part on a square box.
ON_TOP = 0.8
# Elements that paint nothing of their own.
NOT_PAINT = ("defs", "mask", "clipPath", "pattern", "symbol", "linearGradient", "radialGradient", "marker")
SHAPES = ("path", "circle", "rect", "ellipse", "polygon", "polyline", "line", "use")


def _local_name(el):
    return el.tag.split("}")[-1]


def _declared(el, prop):
    """A paint property as the element itself declares it, style over attribute."""
    style = el.get("style") or ""
    found = re.search(r"(?:^|;)\s*%s\s*:\s*([^;]+)" % prop, style)
    return found.group(1).strip() if found else el.get(prop)


def _gradient_colour(root, ref):
    """The colour in the middle of a gradient, following `href` to the gradient
    whose stops it borrows."""
    by_id = {el.get("id"): el for el in root.iter() if el.get("id")}
    grad = by_id.get(ref)
    while grad is not None:
        stops = [s for s in grad if _local_name(s) == "stop"]
        if stops:
            def offset(stop):
                text = stop.get("offset", "0").strip()
                return float(text[:-1]) / 100 if text.endswith("%") else float(text)
            mid = min(stops, key=lambda s: abs(offset(s) - 0.5))
            return _declared(mid, "stop-color")
        href = grad.get("href") or grad.get("{http://www.w3.org/1999/xlink}href")
        grad = by_id.get(href[1:]) if href else None
    return None


def roles(root, slug):
    """Mark every painted part of a mark as ink or cut-out for a lit tile.

    Each part's fill (and stroke) is rewritten to `var(--mark-ink, <own>)` or
    `var(--mark-cut, <own>)`, keeping its own colour at rest. Returns the colours
    that paint straight onto the page, which the light theme may have to deepen,
    and the tile colour: the colour covering most of the mark, cut-outs and
    near-white left out, the middle of a gradient for a gradient.
    """
    if svgelements is None:
        raise SystemExit("roles needs the svgelements package (pip install svgelements)")
    parents = {child: parent for parent in root.iter() for child in parent}

    def hidden(el):
        while el in parents:
            el = parents[el]
            if _local_name(el) in NOT_PAINT:
                return True
        return False

    def inherited(el, prop):
        while el is not None:
            value = _declared(el, prop)
            if value:
                return value
            el = parents.get(el)
        return "#000000" if prop == "fill" else None

    def colour_of(value):
        if not value or value in ("none", "transparent"):
            return None
        ref = re.match(r"url\(#([^)]+)\)", value)
        if ref:
            value = _gradient_colour(root, ref.group(1))
            return _rgb(value) if value else None
        return _rgb(value)

    parts = []
    for index, el in enumerate(el for el in root.iter() if _local_name(el) in SHAPES and not hidden(el)):
        el.set("data-part", str(index))
        fill, stroke = inherited(el, "fill"), inherited(el, "stroke")
        paint = colour_of(fill) or colour_of(stroke)
        if paint:
            parts.append({"el": el, "fill": fill, "stroke": stroke, "rgb": paint})

    handle, path = tempfile.mkstemp(suffix=".svg")
    os.close(handle)
    try:
        io.open(path, "w", encoding="utf-8").write(ET.tostring(root, encoding="unicode"))
        drawing = svgelements.SVG.parse(path)
    finally:
        os.unlink(path)
    boxes = {}
    for element in drawing.elements():
        key = element.values.get("data-part") if hasattr(element, "values") else None
        if key is None or not isinstance(element, svgelements.Shape):
            continue
        try:
            bounds = element.bbox(with_stroke=True)
        except Exception:
            bounds = None
        if bounds:
            boxes[key] = bounds
    for part in parts:
        part["box"] = boxes.get(part["el"].get("data-part"))
    parts =[p for p in parts if p["box"] and (p["box"][2] - p["box"][0]) * (p["box"][3] - p["box"][1]) > 0]
    for el in root.iter():
        el.attrib.pop("data-part", None)

    def area(box):
        return (box[2] - box[0]) * (box[3] - box[1])

    def lies_on(a, b):
        w = min(a[2], b[2]) - max(a[0], b[0])
        h = min(a[3], b[3]) - max(a[1], b[1])
        return w > 0 and h > 0 and w * h / area(a) >= ON_TOP

    def apart(a, b):
        return sum((x - y) ** 2 for x, y in zip(a, b)) ** 0.5 > SAME_SURFACE

    for i, part in enumerate(parts):
        part["depth"] = 0
        for below in reversed(parts[:i]):
            if lies_on(part["box"], below["box"]):
                part["depth"] = below["depth"] + (1 if apart(part["rgb"], below["rgb"]) else 0)
                break
    # A part under a larger one of another colour shows only through that
    # one's holes, as MEGA's white disc shows through the M.
    for i, part in enumerate(parts):
        for above in parts[i + 1:]:
            if lies_on(part["box"], above["box"]) and apart(part["rgb"], above["rgb"]):
                if above["depth"] % 2 == part["depth"] % 2:
                    part["depth"] = above["depth"] + 1
                break

    for part in parts:
        role = "--mark-cut" if part["depth"] % 2 else "--mark-ink"
        el = part["el"]
        for prop in ("fill", "stroke"):
            value = part[prop]
            if not value or value in ("none", "transparent"):
                continue
            wrapped = "var(%s, %s)" % (role, value)
            style = el.get("style") or ""
            if re.search(r"(?:^|;)\s*%s\s*:" % prop, style):
                el.set("style", re.sub(r"((?:^|;)\s*%s\s*:\s*)[^;]+" % prop, lambda m: m.group(1) + wrapped, style))
            else:
                el.set(prop, wrapped)

    ground = {p["rgb"] for p in parts if p["depth"] == 0}
    cover = {}
    for p in parts:
        if p["depth"] % 2 == 0 and min(p["rgb"]) <= 216:
            cover[p["rgb"]] = cover.get(p["rgb"], 0) + area(p["box"])
    # A white shape carrying its detail in colour, like Filen's disc and strokes.
    if not cover:
        for p in parts:
            if min(p["rgb"]) <= 216:
                cover[p["rgb"]] = cover.get(p["rgb"], 0) + area(p["box"])
    tile = "#%02x%02x%02x" % max(cover, key=cover.get) if cover else None
    return ground, tile


def crop_to_ink(component, name):
    """Tighten a mark's viewBox onto its drawing, since a tile scales the box
    and a drawing in a box twice its height arrives at half the size of its
    neighbours."""
    declared, ink = _measure_ink(component, name)
    slack_x = declared[2] / ink[2]
    slack_y = declared[3] / ink[3]
    # `or 0.0` turns a measured -0.0 into 0, so rounding never writes "-0".
    tight = "%s %s %s %s" % tuple(
        (("%.2f" % (round(value, 2) or 0.0)).rstrip("0").rstrip(".") or "0") for value in ink
    )

    if name in INK:
        if slack_x <= SLACK and slack_y <= SLACK:
            REDUNDANT.append((name, INK[name], tight))
        else:
            print("  %s: kept its override %s over the measured %s"
                  % (name, INK[name], tight))
        return component

    if slack_x <= SLACK and slack_y <= SLACK:
        return component
    print("  %s: cropped to its ink (%.2fx wide, %.2fx tall)" % (name, slack_x, slack_y))
    cropped, hits = re.subn(r'viewBox="[^"]*"', 'viewBox="%s"' % tight, component, count=1)
    # The crop has already been announced, so a replacement that misses stops
    # the run.
    if hits != 1:
        raise SystemExit("%s: could not find its viewBox to crop" % name)
    return cropped


def _inline_css(root, slug):
    """Fold an Illustrator `<style>` block into the elements it paints.

    Class names are global to the document, so two marks both defining `.st0`
    would share one fill. This runs before the JSX pass, so a `url(#…)` inside
    a rule gets the same id prefix as every other reference.
    """
    parents = {child: parent for parent in root.iter() for child in parent}
    rules = {}
    for style in [e for e in root.iter() if e.tag == SVG_NS + "style"]:
        text = re.sub(r"/\*.*?\*/", "", style.text or "", flags=re.S)
        for selector, body in re.findall(r"([^{}]+)\{([^{}]*)\}", text):
            for one_selector in selector.split(","):
                one_selector = one_selector.strip()
                if not re.fullmatch(r"\.[-\w]+", one_selector):
                    raise SystemExit(
                        "brand-paths/%s: <style> carries the selector %r, which this "
                        "generator only handles as a plain class" % (slug, one_selector)
                    )
                rules.setdefault(one_selector[1:], []).append(body.strip().strip(";"))
        parents[style].remove(style)

    for el in root.iter():
        names = (el.get("class") or "").split()
        if not names:
            continue
        del el.attrib["class"]
        # The element's own `style` wins, so it goes last.
        declarations = [d for n in names for d in rules.get(n, [])]
        if el.get("style"):
            declarations.append(el.get("style").strip().strip(";"))
        if declarations:
            el.set("style", "; ".join(declarations))
    return root


def _single_ink(path, slug):
    """The one colour a monochrome file paints with, black when it names none.
    A pair half with a second colour is refused."""
    text = io.open(path, encoding="utf-8").read()
    colours = {c.lower() for c in re.findall(r"#[0-9a-fA-F]{3,6}", text)}
    if len(colours) > 1:
        raise SystemExit("%s paints in %d colours; a pair half must be one ink" % (path.name, len(colours)))
    if not colours:
        return "#000000"  # no fill named anywhere: SVG's own default
    ink = colours.pop()
    return "#" + "".join(c * 2 for c in ink[1:]) if len(ink) == 4 else ink


def pair(name, slug, note, source, licence):
    """One drawing supplied in two inks, picked by theme rather than computed.
    `-dark` is the dark ink, for a light ground; `-light` the white one, for a
    dark ground."""
    dark_file = BRAND_DIR / (slug + "-dark.svg")
    light_file = BRAND_DIR / (slug + "-light.svg")
    dark_ink = _single_ink(dark_file, slug)
    light_ink = _single_ink(light_file, slug)

    geometry = [re.findall(r'\sd="([^"]+)"', io.open(f, encoding="utf-8").read()) for f in (dark_file, light_file)]
    if geometry[0] != geometry[1] or not geometry[0]:
        raise SystemExit("%s: the two inks are not the same drawing" % slug)

    root = _inline_css(ET.fromstring(io.open(dark_file, encoding="utf-8").read()), slug)
    box = root.get("viewBox")
    if not box:
        raise SystemExit("brand-paths/%s-dark.svg has no viewBox" % slug)

    variable = "--brand-%s-0" % slug
    VARIABLES.append((variable, light_ink, dark_ink))
    # The ink drawn for a light ground is the brand's own.
    tile(name, slug, dark_ink)

    # Every shape takes its fill from the root, so one geometry serves both inks.
    ids = {}
    body = "\n".join(c for c in (_jsx(k, ids, slug, 3) for k in root) if c)
    body = re.sub(r'\s+fill="[^"]*"', "", body)

    return f'''/** {note}. Source: {source} ({licence}), in both its inks */
export function {name}(props: SVGProps<SVGSVGElement>) {{
  return (
    <svg viewBox="{box}" width="1em" height="1em" fill="var(--mark-ink, var({variable}))" aria-hidden {{...props}}>
{body}
    </svg>
  )
}}
'''


def local(name, slug, note, source, licence):
    if not (BRAND_DIR / (slug + ".svg")).is_file():
        return pair(name, slug, note, source, licence)
    path = BRAND_DIR / (slug + ".svg")
    root = _inline_css(ET.fromstring(io.open(path, encoding="utf-8").read()), slug)

    # The source's box, or one built from width and height, since a component
    # without a viewBox does not scale to 1em.
    box = root.get("viewBox")
    if not box:
        w, h = root.get("width"), root.get("height")
        if not w or not h:
            raise SystemExit("brand-paths/%s.svg has neither viewBox nor size" % slug)
        box = "0 0 %s %s" % (w, h)

    plate = _drop_plate(root, path, slug)
    ground, largest = roles(root, slug)
    tile(name, slug, largest or plate)

    ids = {}
    for el in root.iter():
        if el.get("id"):
            ids[el.get("id")] = "%s-%s" % (slug, el.get("id"))

    kids = [c for c in (_jsx(k, ids, slug, 3) for k in root) if c]
    if not kids:
        raise SystemExit("brand-paths/%s.svg is empty" % slug)
    body = "\n".join(kids)

    # The root's painting attributes come along: Yandex's whole colour is a
    # `fill` on the `<svg>`.
    skip = {"viewBox", "width", "height", "id", "class", "role", "style", "x", "y"}
    root_attrs = []
    for raw, value in root.attrib.items():
        if raw.startswith("{") or raw in skip or _camel(raw) in ("xmlns", "xmlnsXlink", "version"):
            continue
        root_attrs.append('%s="%s"' % (_camel(raw), value))

    # What the mark paints with. A `<mask>`'s white and black are not ink and
    # would mislead the readability check.
    painted_text = re.sub(r"<mask\b.*?</mask>", " ", body, flags=re.S) + " " + " ".join(root_attrs)
    found = re.findall(
        r'"(#[0-9a-fA-F]{3,8}|rgb\([^"]*\)|%s)"' % "|".join(KEYWORDS),
        painted_text,
    ) + re.findall(
        r'--mark-(?:ink|cut), (#[0-9a-fA-F]{3,8}|rgb\([^)]*\)|%s)\)' % "|".join(KEYWORDS),
        painted_text,
    )

    # Any other word where a colour belongs would be skipped by the readability
    # check, so it is refused.
    for attribute in ("fill", "stroke"):
        for value in re.findall(r'%s="([^"]*)"' % attribute, painted_text):
            if value in ("none", "currentColor", "transparent") or value.startswith("var(") \
                    or value.startswith("url(") or value.startswith("#") \
                    or value.startswith("rgb") or value.lower() in KEYWORDS:
                continue
            raise SystemExit(
                "%s paints with %s=\"%s\", which nothing here can measure. Add it to "
                "KEYWORDS with its hex, or give the file a real colour." % (slug, attribute, value)
            )
    # A file naming no colour paints in SVG's default black, which the
    # readability check has to see.
    if not found:
        root_attrs.append('fill="#000000"')
        found = ["#000000"]

    swap = themed(found, slug, ground)
    body = apply_swap(body, swap)
    root_attrs = [apply_swap(a, swap) for a in root_attrs]
    painted = ("".join(" " + a for a in root_attrs))

    # Fills, styles, gradients and groups stay as drawn.
    return f'''/** {note}. Source: {source} ({licence}) */
export function {name}(props: SVGProps<SVGSVGElement>) {{
  return (
    <svg viewBox="{box}"{painted} width="1em" height="1em" aria-hidden {{...props}}>
{body}
    </svg>
  )
}}
'''


CSS_OUT = Path(__file__).parent.parent / "web" / "src" / "brandGlyphs.css"

CSS_HEAD = """/* Brand marks that need a different lightness on one of the two grounds.
   GENERATED by scripts/gen_brand_glyphs.py, do not hand-edit.

   A mark drawn in navy or black is invisible on a dark surface, a part in
   near-white on a light one. Such a colour is a custom property whose
   lightness is shifted on that ground only, keeping its hue and saturation.
   The generator decides which colours need it by measurement.

   The three blocks mirror tokens.css: dark by default, light when the OS asks
   and nothing overrides it, light when the app is set to it.
*/
"""


def with_hover(component, name, slug):
    """A mark followed by the brand's single-colour mark, which a lit tile shows
    in its place (.glim-mark-rest and .glim-mark-hover in tokens.css)."""
    svg = io.open(SRC / (slug + ".svg"), encoding="utf-8").read()
    box = re.search(r'viewBox="([^"]+)"', svg).group(1)
    paths = "\n".join('      <path d="%s" />' % d for d in re.findall(r'<path d="([^"]+)"', svg))
    hover = crop_to_ink(
        '<svg viewBox="%s" width="1em" height="1em" fill="currentColor" aria-hidden {...props}>\n%s\n    </svg>'
        % (box, paths), name + " (hover)")
    rest = component[component.index("<svg"):component.rindex("</svg>") + 6]
    both = "<>\n    %s\n    %s\n    </>" % (
        rest.replace("<svg ", '<svg className="glim-mark-rest" ', 1),
        hover.replace("<svg ", '<svg className="glim-mark-hover" ', 1),
    )
    return component.replace(rest, both)


def css_block(selectors, index, indent=0):
    """One rule: its selectors, one custom property per mark, closing brace."""
    pad = " " * indent
    lines = ["%s%s," % (pad, s) for s in selectors[:-1]]
    lines.append("%s%s {" % (pad, selectors[-1]))
    for name, on_dark, on_light in VARIABLES:
        lines.append("%s  %s: %s;" % (pad, name, on_dark if index == 1 else on_light))
    lines.append("%s}" % pad)
    return "\n".join(lines)


known = {m[0] for m in MARKS} | {m[0] for m in LOCAL}
unknown = sorted(set(INK) - known)
if unknown:
    raise SystemExit("INK names marks that do not exist: " + ", ".join(unknown))

if not SRC.is_dir():
    raise SystemExit("no such directory: %s\nInstall simple-icons and pass its icons path." % SRC)

components = [one(*m) for m in MARKS] + [local(*m) for m in LOCAL]
# Cropping runs last, over the finished markup the app draws.
components = [crop_to_ink(c, m[0]) for c, m in zip(components, MARKS + LOCAL)]
if REDUNDANT:
    raise SystemExit(
        "These INK overrides only restate what the measurement already found. "
        "Delete them:\n" + "\n".join(
            "  %s: %r (measured %r)" % row for row in REDUNDANT
        )
    )
components = [
    with_hover(c, m[0], HOVER[m[0]]) if m[0] in HOVER else c
    for c, m in zip(components, MARKS + LOCAL)
]
tiles = "\n".join(
    "  %s: { tile: '%s', ink: '%s' }," % (name, colour, ink) for name, (colour, ink) in TILES.items()
)
parts = [HEAD] + components + [
    "/** What each mark's tile lights up in under the pointer: the brand's own colour\n"
    " *  and the ink that holds on it (\"Brand tiles\" in GlimStone). */\n"
    "export const BRAND_TILES: Record<string, { tile: string; ink: string }> = {\n%s\n}\n" % tiles
]
io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(parts))

css = [CSS_HEAD]
if VARIABLES:
    css.append(css_block([":root", '[data-theme="dark"]'], 1))
    css.append(
        "@media (prefers-color-scheme: light) {\n"
        + css_block([':root:not([data-theme="dark"])'], 2, indent=2)
        + "\n}"
    )
    css.append(css_block(['[data-theme="light"]'], 2))
io.open(CSS_OUT, "w", encoding="utf-8", newline="\n").write("\n\n".join(css) + "\n")

flipped = sorted({name.rsplit("-", 1)[0][8:] for name, _, _ in VARIABLES})
print("%s: %d marks (%d from Simple Icons, %d local)" % (OUT.name, len(MARKS) + len(LOCAL), len(MARKS), len(LOCAL)))
print("%s: %d variables for %d marks (%s)" % (CSS_OUT.name, len(VARIABLES), len(flipped), ", ".join(flipped)))
