"""Generate the provider marks from Simple Icons.

    npm install simple-icons@16 somewhere, then:
    python scripts/gen_brand_glyphs.py <path to simple-icons/icons>

Simple Icons is CC0, so a mark taken from it carries no attribution duty. The
trademarks themselves remain their owners': every mark here is used to NAME the
service it belongs to, on a row that connects to exactly that service, which is
the one use of a trademark that needs no permission. Each is reproduced
unmodified apart from being given `currentColor`, and nothing about any of them
claims endorsement or affiliation.

Generated rather than transcribed for the same reason every other generator in
this repo exists: twenty-five hand-copied paths drift from their source the
first time one is touched, and a wrong brand mark is worse than none.

WRITES web/src/components/brandGlyphs.tsx, which also holds the GitHub mark that
was added by hand before this script existed - so the file is regenerated whole
and the GitHub entry is part of the table below rather than being preserved.
"""
import io
import json
import os
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

SRC = Path(sys.argv[1] if len(sys.argv) > 1 else
           "C:/Users/JUNKER~1/AppData/Local/Temp/si/node_modules/simple-icons/icons")
OUT = Path(__file__).parent.parent / "web" / "src" / "components" / "brandGlyphs.tsx"

# Our component name -> the Simple Icons slug, with what it is for.
#
# Several are a judgement call and are marked as such: a mark that names the
# right COMPANY but not the exact product is better than no mark, and a mark
# that names a DIFFERENT product is not. Where the second was the only option,
# the entry is left out and the provider shows a generic glyph instead.
MARKS = [
    ("IconGithub", "github", "This project's own repository"),

    # The self-hosted three. OpenCloud is a fork of ownCloud and has no mark of
    # its own here; it deliberately gets none rather than wearing ownCloud's,
    # which would name the wrong project.
    ("IconNextcloud", "nextcloud", "Nextcloud"),
    ("IconOwncloud", "owncloud", "ownCloud"),

    # The consumer services.
    ("IconDropbox", "dropbox", "Dropbox"),
    ("IconGoogleDrive", "googledrive", "Google Drive"),
    ("IconGooglePhotos", "googlephotos", "Google Photos"),
    ("IconGoogleCloud", "googlecloud", "Google Cloud Storage"),
    ("IconMega", "mega", "MEGA"),
    ("IconBox", "box", "Box"),
    ("IconProtonDrive", "protondrive", "Proton Drive"),
    ("IconICloud", "icloud", "iCloud Drive"),
    ("IconMailru", "maildotru", "Mail.ru Cloud"),
    ("IconYandex", "yandexcloud", "Yandex Disk"),
    ("IconZoho", "zoho", "Zoho WorkDrive"),
    ("IconSeafile", "seafile", "Seafile"),
    ("IconFilen", "filen", "Filen"),
    ("IconFilesCom", "files", "Files.com"),
    ("IconHuawei", "huawei", "Huawei Drive"),
    # HiDrive is IONOS's product and carries no separate mark here.
    ("IconIonos", "ionos", "HiDrive, which is IONOS's"),
    # ShareFile was Citrix's and the mark is still filed under the parent.
    ("IconCitrix", "citrix", "ShareFile, filed under Citrix"),

    # Object storage and infrastructure.
    ("IconBackblaze", "backblaze", "Backblaze B2"),
    ("IconOpenstack", "openstack", "OpenStack Swift"),
    ("IconAkamai", "akamai", "Akamai NetStorage"),
    ("IconHadoop", "apachehadoop", "HDFS"),

    # Media and archives.
    ("IconInternetArchive", "internetarchive", "Internet Archive"),
    ("IconCloudinary", "cloudinary", "Cloudinary"),
]

HEAD = '''import type { SVGProps } from 'react'

// ---------------------------------------------------------------------------
// Brand marks. GENERATED by scripts/gen_brand_glyphs.py - do not hand-edit.
//
// Kept apart from `glyphs.tsx` on purpose. That file is one Streamline set,
// drawn on one grid to one convention, which is what makes those icons agree
// with each other. A brand mark cannot come from there: it is somebody else's
// drawing, it must not be redrawn to fit, and it must not be swapped for a
// near neighbour when the set lacks it - a mark naming the WRONG service is
// worse than no mark, which is why several providers here deliberately have
// none.
//
// Source: Simple Icons (simpleicons.org), published under CC0. No attribution
// is required; it is given because knowing where a drawing came from is worth
// more than the licence demands.
//
// TRADEMARKS. Every mark below belongs to its owner. Each is used the one way a
// trademark may be used without permission: to name the thing it refers to. A
// mark appears only on a row that connects to exactly that service, each is
// reproduced unmodified apart from taking `currentColor`, and nothing here
// claims endorsement by or affiliation with any of them.
//
// The design language's other half of this rule: a brand mark is never
// reachable by PATTERN from a translation key. It is passed at the call site
// that means it.
// ---------------------------------------------------------------------------

'''


# The brands' own colours, keyed by slug, from the set's own data file.
COLOURS = {}
_data = SRC.parent / "data" / "simple-icons.json"
if _data.exists():
    import json

    _raw = json.loads(io.open(_data, encoding="utf-8").read())
    for entry in (_raw["icons"] if isinstance(_raw, dict) else _raw):
        title = entry.get("title", "")
        # The slug is the title lowercased with everything but letters and
        # digits removed, which is the set's own rule; a `slug` field overrides
        # it where the two differ.
        s_ = entry.get("slug") or re.sub(r"[^a-z0-9]", "", title.lower())
        COLOURS[s_] = "#" + entry["hex"]


def one(name: str, slug: str, note: str) -> str:
    svg = io.open(SRC / (slug + ".svg"), encoding="utf-8").read()
    box = re.search(r'viewBox="([^"]+)"', svg)
    paths = re.findall(r'<path d="([^"]+)"', svg)
    if not box or not paths:
        raise SystemExit("cannot read %s.svg" % slug)
    colour = COLOURS.get(slug)
    if not colour:
        raise SystemExit("no brand colour for %s: the data file did not carry it" % slug)
    body = "\n".join('      <path d="%s" />' % d for d in paths)
    # The brand's OWN colour rather than currentColor, because a logo drawn in
    # the interface's ink is not the logo, it is a silhouette of it. jdp: "die
    # logos sollen original und farbig sein."
    #
    # Simple Icons draws every mark as one path in one colour, and for most of
    # these that IS the real thing: Dropbox's mark is one blue, Nextcloud's one
    # blue, MEGA's one red. For the few whose official mark is multi-coloured -
    # Google Drive - it is that brand's primary colour rather than its full
    # drawing, which is as close as a CC0 set gets and much closer than grey.
    #
    # `fill` sits on the svg rather than on each path, so one style on the
    # element can still override the whole mark where a surface demands it.
    return f'''/** {note}. Simple Icons: {slug}, in its own {colour} */
export function {name}(props: SVGProps<SVGSVGElement>) {{
  return (
    <svg viewBox="{box.group(1)}" width="1em" height="1em" fill="{colour}" aria-hidden {{...props}}>
{body}
    </svg>
  )
}}
'''


# Marks Simple Icons does not carry, kept as their own SVG under
# scripts/brand-paths/. Each is somebody else's file, reproduced unmodified,
# with its source and its licence recorded here and in that folder's README.
#
# Same trademark reasoning as everything above: used to name the thing it refers
# to, reproduced unmodified, no claim of endorsement. What differs is the
# licence position - these are not CC0 - so each entry carries the licence it
# arrived under, and every one of those licences is satisfied by naming it.
LOCAL = [
    ("IconOpencloud", "opencloud", "OpenCloud",
     "opencloud-eu/opencloud, services/web/assets/themes/opencloud/assets/logo-mobile.svg",
     "the project's own logo, from its own repository"),
    # Dashboard Icons, Apache-2.0. jdp found the set: "hier gibts viele des
    # fehlenden logos: https://dashboardicons.com/". Five of the nineteen marks
    # Simple Icons lacks are in it; the rest are still missing.
    ("IconOnedrive", "microsoft-onedrive", "OneDrive",
     "homarr-labs/dashboard-icons, svg/microsoft-onedrive.svg", "Apache-2.0"),
    # Azure's STORAGE ACCOUNT mark. Blob storage is a service inside a storage
    # account and has no separate mark in this set, so this names the right
    # product family rather than a different product - the same judgement made
    # for HiDrive above, and the same one that keeps OpenCloud off ownCloud's.
    ("IconAzureStorage", "azure-storage-accounts", "Azure Blob Storage, under Azure's storage mark",
     "homarr-labs/dashboard-icons, svg/azure-storage-accounts.svg", "Apache-2.0"),
    ("IconOracleCloud", "oracle-cloud", "Oracle Object Storage, part of Oracle Cloud",
     "homarr-labs/dashboard-icons, svg/oracle-cloud.svg", "Apache-2.0"),
    ("IconStorj", "storj", "Storj",
     "homarr-labs/dashboard-icons, svg/storj.svg", "Apache-2.0"),
    ("IconPremiumize", "premiumize", "premiumize.me",
     "homarr-labs/dashboard-icons, svg/premiumize.svg", "Apache-2.0"),
]

# Attributes that mean nothing inside a component, or that the wrapper sets.
DROP_ROOT = {"xmlns", "version", "width", "height", "id", "class"}

# SVG attribute -> its JSX spelling, where lowercasing the hyphen is not the
# rule. Everything else hyphenated is camelCased below.
SPECIAL = {"class": "className", "for": "htmlFor"}


def _camel(name):
    """`stop-color` -> `stopColor`, but `data-x` and `aria-x` stay put."""
    if name.startswith("data-") or name.startswith("aria-"):
        return name
    if name in SPECIAL:
        return SPECIAL[name]
    head, _, tail = name.partition("-")
    while tail:
        piece, _, rest = tail.partition("-")
        head += piece[:1].upper() + piece[1:]
        tail = rest
    return head


def _style_object(value):
    """`fill:#a00;fill-opacity:1` -> a JSX style object.

    JSX takes an object here, never the CSS string an SVG file carries, and
    several of these marks put their whole colour in a `style` attribute.
    """
    pairs = []
    for chunk in value.split(";"):
        key, sep, val = chunk.partition(":")
        if not sep or not key.strip():
            continue
        pairs.append("%s: %s" % (_camel(key.strip()), json.dumps(val.strip())))
    return "{{ %s }}" % ", ".join(pairs) if pairs else None


def _jsx(node, ids, slug, depth):
    """One SVG element and its children as JSX source, or None to skip it."""
    tag = node.tag.split("}")[-1]
    # <title> and <desc> go, whatever they hold. What they hold is the asset
    # name from whoever drew the file ("Icon-storage-86"), which labels nothing
    # a reader of this interface would want read out, and the wrapper is
    # aria-hidden regardless: the provider's NAME sits next to the mark.
    if tag in ("title", "desc"):
        return None
    pad = "  " * depth
    attrs = []
    for raw, value in node.attrib.items():
        # `xlink:href` arrives fully qualified and is `xlinkHref` in JSX.
        if raw.startswith("{http://www.w3.org/1999/xlink}"):
            key = "xlinkHref"
        elif raw.startswith("{"):
            continue  # any other foreign namespace means nothing to the DOM here
        else:
            key = _camel(raw)
        if key in ("xmlns", "xmlnsXlink", "version"):
            continue
        # Every id in the file is rewritten, because two marks on one page that
        # both define `radial0` would collide: `url(#radial0)` resolves to
        # whichever came first in the document, so one logo would wear the
        # other's gradient. Prefixing with the slug makes each file's ids its
        # own.
        if key == "id":
            value = ids[value]
        else:
            for old, new in ids.items():
                value = value.replace("url(#%s)" % old, "url(#%s)" % new)
                if value == "#" + old:
                    value = "#" + new
        if key == "style":
            obj = _style_object(value)
            if not obj:
                continue
            attrs.append("style=%s" % obj)
            continue
        attrs.append("%s=%s" % (key, '"%s"' % value if '"' not in value else "{%s}" % json.dumps(value)))
    head = ("<%s " % tag) + " ".join(attrs) if attrs else "<%s" % tag
    # Text would be silently swallowed otherwise, which is how an <title> full
    # of somebody's asset name came through this generator as an empty tag.
    # Nothing among these marks draws with <text>; if one ever does, it should
    # stop the build rather than lose its lettering.
    if (node.text or "").strip():
        raise SystemExit("brand-paths/%s.svg: <%s> carries text this generator drops" % (slug, tag))

    kids = [c for c in (_jsx(k, ids, slug, depth + 1) for k in node) if c]
    if not kids:
        return "%s%s />" % (pad, head)
    return "%s%s>\n%s\n%s</%s>" % (pad, head, "\n".join(kids), pad, tag)


def local(name, slug, note, source, licence):
    path = Path(__file__).parent / "brand-paths" / (slug + ".svg")
    root = ET.fromstring(io.open(path, encoding="utf-8").read())

    # The box: its own if it has one, otherwise built from width and height.
    # Several of these carry only a size, and a component with no viewBox does
    # not scale to the 1em the interface asks for.
    box = root.get("viewBox")
    if not box:
        w, h = root.get("width"), root.get("height")
        if not w or not h:
            raise SystemExit("brand-paths/%s.svg has neither viewBox nor size" % slug)
        box = "0 0 %s %s" % (w, h)

    ids = {}
    for el in root.iter():
        if el.get("id"):
            ids[el.get("id")] = "%s-%s" % (slug, el.get("id"))

    kids = [c for c in (_jsx(k, ids, slug, 3) for k in root) if c]
    if not kids:
        raise SystemExit("brand-paths/%s.svg is empty" % slug)
    body = "\n".join(kids)

    # Whatever the file paints WITH stays: `fill`, `style`, gradients, groups
    # and all. A mark drawn in several tones is several tones, and flattening
    # one to a single ink would be redrawing somebody's logo.
    return f'''/** {note}. Source: {source} ({licence}) */
export function {name}(props: SVGProps<SVGSVGElement>) {{
  return (
    <svg viewBox="{box}" width="1em" height="1em" aria-hidden {{...props}}>
{body}
    </svg>
  )
}}
'''


if not SRC.is_dir():
    raise SystemExit("no such directory: %s\nInstall simple-icons and pass its icons path." % SRC)

parts = [HEAD] + [one(*m) for m in MARKS] + [local(*m) for m in LOCAL]
io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(parts))
print("%s: %d marks (%d from Simple Icons, %d local)" % (OUT.name, len(MARKS) + len(LOCAL), len(MARKS), len(LOCAL)))
