"""Turn the logo SVG into the React component the job cards use as a status mark.

Run it again after any change to `web/public/favicon.svg`.

The rings are gold in four depths and carry the status colour, so the four gold
classes become `currentColor` mixed to four depths. The arrow keeps its greys,
since it is what makes the mark recognisable.

Shapes keep the drawing's own order, because they overlap. Each class is
resolved into a fill attribute, since an inline <style> with names as generic
as `.cls-1` would repaint anything else on the page that uses them.
"""
import io
import re
import sys
from pathlib import Path

SRC = Path("web/public/favicon.svg")
OUT = Path("web/src/components/LogoMark.tsx")

# Mixed in oklab, since an srgb mix towards black turns a yellow muddy long
# before it turns dark.
RING = {
    "#f9d68f": "color-mix(in oklab, currentColor 55%, white)",
    "#e6bc59": "currentColor",
    "#ba8331": "color-mix(in oklab, currentColor 78%, black)",
    "#755934": "color-mix(in oklab, currentColor 46%, black)",
}

src = io.open(SRC, encoding="utf-8").read()

classes = {k: v.lower() for k, v in re.findall(r"\.(cls-\d+)\s*\{\s*fill:\s*(#[0-9a-fA-F]+);", src)}
if not classes:
    sys.exit("no fill classes found in " + str(SRC))

box = re.search(r'viewBox="([^"]+)"', src)
if not box:
    sys.exit("no viewBox in " + str(SRC))

ring_lines, arrow_lines, order = [], [], []
for m in re.finditer(r'<(path|polygon)\s+class="(cls-\d+)"\s+(d|points)="([^"]+)"\s*/?>', src):
    tag, cls, attr, data = m.groups()
    colour = classes.get(cls)
    if colour is None:
        sys.exit(f"shape uses {cls}, which the style block does not define")
    if colour in RING:
        ring_lines.append(f'        <{tag} fill="{RING[colour]}" {attr}="{data}" />')
        order.append("ring")
    else:
        arrow_lines.append(f'        <{tag} fill="{colour}" {attr}="{data}" />')
        order.append("arrow")

shapes = src.count("<path") + src.count("<polygon")
if len(order) != shapes:
    sys.exit(f"matched {len(order)} of {shapes} shapes; the source's markup shape changed")
if not ring_lines or not arrow_lines:
    sys.exit(f"expected both materials, got {len(ring_lines)} ring and {len(arrow_lines)} arrow shapes")

# Two groups let the arrow move on its own, which is only safe while every ring
# shape comes before every arrow shape; grouping interleaved shapes would change
# what covers what.
if order != ["ring"] * len(ring_lines) + ["arrow"] * len(arrow_lines):
    sys.exit(
        "the drawing now interleaves rings and arrow shapes, so splitting them into "
        "two groups would change what covers what; group them in the SVG instead"
    )

body = f'''import type {{ CSSProperties }} from 'react'

/**
 * The rings' gold when they carry no status, taken from the drawing. Set as
 * `color`, it makes the mark exactly the logo again.
 */
export const LOGO_GOLD = '{[k for k, v in RING.items() if v == "currentColor"][0]}'

/**
 * The app's own mark, with rings that carry a status colour.
 *
 * GENERATED by scripts/gen_logo_mark.py from web/public/favicon.svg. Do not
 * edit by hand: change the drawing and run the script again.
 *
 * The rings are `currentColor` mixed in oklab to the drawing's four depths; the
 * arrow keeps its greys. `.al-logo-rings` and `.al-logo-arrow` are separate
 * groups so the arrow can leave the rings and fly back (`.al-logo-loose` in
 * index.css).
 */
export function LogoMark({{
  size = 28,
  className = '',
  style,
  title,
}}: {{
  size?: number
  className?: string
  style?: CSSProperties
  title?: string
}}) {{
  return (
    <svg
      viewBox="{box.group(1)}"
      width={{size}}
      height={{size}}
      className={{className}}
      style={{style}}
      role={{title ? 'img' : 'presentation'}}
      aria-label={{title}}
      aria-hidden={{title ? undefined : true}}
      focusable="false"
    >
      {{/* The rings, in the current colour at the drawing's own four depths. */}}
      <g className="al-logo-rings">
{chr(10).join(ring_lines)}
      </g>
      {{/* The arrow, in its own greys, in every state. */}}
      <g className="al-logo-arrow">
{chr(10).join(arrow_lines)}
      </g>
    </svg>
  )
}}
'''

io.open(OUT, "w", encoding="utf-8", newline="\n").write(body)
print(f"{OUT}: {len(ring_lines)} ring shapes, {len(arrow_lines)} arrow shapes, {shapes} total, {len(body)} bytes")
