"""Turn the logo SVG into the React component the job cards use as a status mark.

Generated rather than typed, for the reason every generator in this repo exists:
the drawing is the master, and a hand-copied copy of two dozen shapes drifts
from it the first time the logo is touched. Run it again after any change to
`web/public/favicon.svg`.

The one thing this does beyond copying: it splits the drawing's two materials.
The rings are gold in four depths and the arrow is grey in three, and jdp asked
for the rings to carry the status colour ("du kannst die ringe nach status
einfaerbig einfaerben"). So the four gold classes become one `currentColor`
mixed to four depths, and the greys are left exactly as they are - the arrow is
what makes the mark recognisable as this program's, and an arrow tinted red is
somebody else's logo.

Shapes are emitted IN THE DRAWING'S OWN ORDER, paths and polygons together.
They overlap, so sorting them by material would put the arrow's fletching
behind the rings. The class-to-fill mapping in the source's <style> block is
resolved into a fill attribute on each shape, because an inline <style> with
names as generic as `.cls-1` is global to the page and would repaint anything
else that happens to use them.
"""
import io
import re
import sys
from pathlib import Path

SRC = Path("web/public/favicon.svg")
OUT = Path("web/src/components/LogoMark.tsx")

# The four gold classes and what each becomes. Mixed in oklab rather than srgb
# so a mid-tone stays a mid-tone at every hue the palette can produce: a
# straight srgb mix towards black turns a yellow muddy long before it turns
# dark.
RING = {
    "#f9d68f": "color-mix(in oklab, currentColor 55%, white)",
    "#e6bc59": "currentColor",
    "#ba8331": "color-mix(in oklab, currentColor 78%, black)",
    "#755934": "color-mix(in oklab, currentColor 46%, black)",
}

src = io.open(SRC, encoding="utf-8").read()

classes = {k: v.lower() for k, v in re.findall(r"\.(cls-\d+)\s*\{\s*fill:\s*(#[0-9a-fA-F]+);", src)}
if not classes:
    sys.exit("no fill classes found in " + str(SRC))

box = re.search(r'viewBox="([^"]+)"', src)
if not box:
    sys.exit("no viewBox in " + str(SRC))

ring_lines, arrow_lines, order = [], [], []
for m in re.finditer(r'<(path|polygon)\s+class="(cls-\d+)"\s+(d|points)="([^"]+)"\s*/?>', src):
    tag, cls, attr, data = m.groups()
    colour = classes.get(cls)
    if colour is None:
        sys.exit(f"shape uses {cls}, which the style block does not define")
    if colour in RING:
        ring_lines.append(f'        <{tag} fill="{RING[colour]}" {attr}="{data}" />')
        order.append("ring")
    else:
        arrow_lines.append(f'        <{tag} fill="{colour}" {attr}="{data}" />')
        order.append("arrow")

shapes = src.count("<path") + src.count("<polygon")
if len(order) != shapes:
    sys.exit(f"matched {len(order)} of {shapes} shapes; the source's markup shape changed")
if not ring_lines or not arrow_lines:
    sys.exit(f"expected both materials, got {len(ring_lines)} ring and {len(arrow_lines)} arrow shapes")

# The two materials go into two groups so each can be moved on its own, which is
# what the easter egg needs: the arrow leaves the rings and comes back. That is
# only safe because the drawing already puts every ring shape before every arrow
# shape - grouping shapes that INTERLEAVE would silently reorder them and put
# the fletching behind a ring. Checked rather than assumed, because a redrawn
# logo could interleave them and nothing else here would notice.
if order != ["ring"] * len(ring_lines) + ["arrow"] * len(arrow_lines):
    sys.exit(
        "the drawing now interleaves rings and arrow shapes, so splitting them into "
        "two groups would change what covers what; group them in the SVG instead"
    )

body = f'''import type {{ AnimationEventHandler, CSSProperties }} from 'react'

/**
 * The gold the rings are drawn in when they are NOT carrying a status.
 *
 * Exported rather than written out wherever the plain logo appears, and taken
 * from the drawing by this generator, so the rail's copy of the mark cannot
 * drift to a different gold than the file it came from. It is the value that
 * `currentColor` stands in for: set it as `color` and the mark is exactly the
 * logo again.
 */
export const LOGO_GOLD = '{[k for k, v in RING.items() if v == "currentColor"][0]}'

/**
 * The app's own mark, drawn so that its rings can carry a status colour.
 *
 * GENERATED by scripts/gen_logo_mark.py from web/public/favicon.svg. Do not
 * edit by hand: change the drawing and run the script again.
 *
 * The logo is two materials. The rings are gold in four depths and the arrow is
 * grey in three, and only one of those can take a status hue without the mark
 * stopping being this mark. jdp: "du kannst die ringe nach status einfaerbig
 * einfaerben". So the rings are `currentColor` mixed to the four depths the
 * drawing had, and the arrow keeps its own greys - it is the half that makes
 * the logo recognisable, and a red arrow is somebody else's logo.
 *
 * Mixed in oklab rather than srgb: a mid-tone has to stay a mid-tone at every
 * hue the palette can produce, and an srgb mix towards black turns a yellow
 * muddy well before it turns dark.
 *
 * The two materials are also two GROUPS, `.al-logo-rings` and
 * `.al-logo-arrow`, so each can be moved without the other. That is what lets
 * the arrow leave the rings and fly back into them; see `.al-logo-loose` in
 * index.css.
 */
export function LogoMark({{
  size = 28,
  className = '',
  style,
  title,
  onAnimationEnd,
}}: {{
  size?: number
  className?: string
  style?: CSSProperties
  title?: string
  /**
   * Told when an animation on this drawing finishes.
   *
   * Here so a caller can take its own animating class off again when the
   * movement is over, rather than leaving it on for the rest of the session.
   * A class that goes on once and never comes off makes the element's state
   * unreadable: "is it flying" and "has it ever flown" become the same
   * question, which is how the easter egg's own timing bug survived being
   * measured.
   */
  onAnimationEnd?: AnimationEventHandler<SVGSVGElement>
}}) {{
  return (
    <svg
      viewBox="{box.group(1)}"
      width={{size}}
      height={{size}}
      className={{className}}
      style={{style}}
      onAnimationEnd={{onAnimationEnd}}
      role={{title ? 'img' : 'presentation'}}
      aria-label={{title}}
      aria-hidden={{title ? undefined : true}}
      focusable="false"
    >
      {{/* The rings, in the current colour at the drawing's own four depths. */}}
      <g className="al-logo-rings">
{chr(10).join(ring_lines)}
      </g>
      {{/* The arrow, in its own greys, in every state. */}}
      <g className="al-logo-arrow">
{chr(10).join(arrow_lines)}
      </g>
    </svg>
  )
}}
'''

io.open(OUT, "w", encoding="utf-8", newline="\n").write(body)
print(f"{OUT}: {len(ring_lines)} ring shapes, {len(arrow_lines)} arrow shapes, {shapes} total, {len(body)} bytes")
