"""Generate ArrowLoop's icon set from Streamline's FREE Core Solid subset.

Run from the repository root:
    python scripts/gen_glyphs.py <path to streamline-vectors/core/solid>

Source: github.com/webalys-hq/streamline-vectors, folder core/solid, CC BY 4.0.
That is the free 1000-icon subset, whose licence permits redistribution. The
5771-icon set sold on streamlinehq.com is a DIFFERENT, PREMIUM product whose
licence forbids exactly what a public repository does; it must not be used here.

Why this set and nothing else. The design language's sizing rules exist because
MIXING sets produces four different ideas about how much of a viewBox a drawing
should occupy, and the fix for that is a measured, ink-cropped viewBox per
glyph, which needs a real browser to measure. Every icon here comes from one
set drawn on one 14-unit grid with one convention, so the problem the crop
solves does not arise: the source viewBox is carried through unchanged and the
glyphs agree because they were drawn to agree. The day this app needs a glyph
Streamline does not have is the day it also needs the measuring step, and the
comment above the table below says so at the place where somebody would add it.

Writes src/components/glyphs.tsx, which is GENERATED. Do not hand-edit it:
regenerate, or the next run silently discards the change.
"""

import io
import os
import re
import sys

SRC = sys.argv[1] if len(sys.argv) > 1 else "/tmp/slv/core/solid"
OUT = os.path.join(os.path.dirname(__file__), "..", "web", "src", "components", "glyphs.tsx")

# our name -> (file under core/solid, what it means here)
#
# One source set only. Adding a glyph from anywhere else means adding the
# ink-measuring step this generator deliberately does not have; see the module
# docstring before reaching for a second set.
GLYPHS = [
    # Navigation.
    ("IconJobs", "interface-essential/arrow-reload-horizontal-1.svg",
     "Jobs: two arrows, one each way, which is the whole product"),
    ("IconEdit", "interface-essential/pencil.svg", "Edit"),
    ("IconTargets", "computer-devices/database-server-1.svg", "Storage targets and drives"),
    ("IconHistory", "interface-essential/bullet-list.svg", "What the runs did"),
    ("IconLook", "interface-essential/color-palette.svg", "Theme, shape, accent, language"),

    # Row actions. Small, secondary, icon-only: the design language's rule 13.
    ("IconCheck", "interface-essential/magnifying-glass.svg", "Open a target and look at it"),
    ("IconDelete", "interface-essential/recycle-bin-2.svg", "Delete"),
    ("IconCopy", "interface-essential/copy-paste.svg", "Copy to the clipboard"),
    ("IconForget", "interface-essential/subtract-circle.svg", "Forget a drive, leaving its marker"),
    ("IconPreview", "interface-essential/visible.svg", "See what a run would do"),

    # The direction of a job, drawn rather than described. Three glyphs, so the
    # setting reads at a glance from the list without opening anything.
    ("IconBothWays", "interface-essential/arrow-reload-horizontal-1.svg", "Both ways"),
    ("IconToRight", "interface-essential/move-right.svg", "Left to right only"),
    ("IconToLeft", "interface-essential/move-left.svg", "Right to left only"),
]

HEADER = '''// ArrowLoop's icon set.
//
// GENERATED by scripts/gen_glyphs.py. Do not hand-edit: regenerate instead, or
// the next run silently discards the change.
//
// Attribution, required by the licence:
//   Free icons from Streamline - https://streamlinehq.com (CC BY 4.0)
//   The FREE 1000-icon Core Solid subset only:
//   https://github.com/webalys-hq/streamline-vectors
//
// Every glyph here comes from that one set, drawn on one 14-unit grid with one
// convention, which is why none of them needs the measured ink-crop the design
// language describes for apps that mix sets.

import type { SVGProps } from 'react'

/** One glyph. Sized by the caller through width and height, coloured by
 *  currentColor so it follows whatever the surrounding text is doing. */
function Glyph({ box, paths, ...rest }: { box: string; paths: string[] } & SVGProps<SVGSVGElement>) {
  return (
    <svg
      width="14"
      height="14"
      viewBox={box}
      fill="currentColor"
      className="shrink-0"
      aria-hidden="true"
      {...rest}
    >
      {paths.map((one) => (
        <path key={one} fillRule="evenodd" clipRule="evenodd" d={one} />
      ))}
    </svg>
  )
}
'''


def paths_of(svg: str):
    """Every path's d attribute, in document order."""
    return re.findall(r'<path[^>]*\sd="([^"]+)"', svg)


def box_of(svg: str) -> str:
    found = re.search(r'viewBox="([^"]+)"', svg)
    if not found:
        raise SystemExit("no viewBox")
    return found.group(1)


def main() -> None:
    out = [HEADER]
    for name, rel, note in GLYPHS:
        full = os.path.join(SRC, rel)
        if not os.path.exists(full):
            raise SystemExit("missing source glyph: %s" % full)
        svg = io.open(full, encoding="utf-8").read()
        paths = paths_of(svg)
        if not paths:
            raise SystemExit("no paths in %s" % rel)
        joined = ", ".join("'%s'" % p.replace("\\", "\\\\").replace("'", "\\'") for p in paths)
        out.append(
            "\n/** %s. Streamline: %s */\n"
            "export function %s(props: SVGProps<SVGSVGElement>) {\n"
            "  return <Glyph box=\"%s\" paths={[%s]} {...props} />\n"
            "}\n" % (note, rel, name, box_of(svg), joined)
        )
    with open(OUT, "w", encoding="utf-8", newline="") as f:
        f.write("".join(out))
    print("wrote %s with %d glyphs" % (OUT, len(GLYPHS)))


if __name__ == "__main__":
    main()
