"""Generate the provider marks from Simple Icons.

    npm install simple-icons@16 somewhere, then:
    python scripts/gen_brand_glyphs.py <path to simple-icons/icons>

Simple Icons is CC0, so a mark taken from it carries no attribution duty. The
trademarks themselves remain their owners': every mark here is used to NAME the
service it belongs to, on a row that connects to exactly that service, which is
the one use of a trademark that needs no permission. Each is reproduced
unmodified apart from being given `currentColor`, and nothing about any of them
claims endorsement or affiliation.

Generated rather than transcribed for the same reason every other generator in
this repo exists: twenty-five hand-copied paths drift from their source the
first time one is touched, and a wrong brand mark is worse than none.

WRITES web/src/components/brandGlyphs.tsx, which also holds the GitHub mark that
was added by hand before this script existed - so the file is regenerated whole
and the GitHub entry is part of the table below rather than being preserved.
"""
import colorsys
import io
import json
import os
import os
import re
import sys
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path

# The only third-party thing this generator needs, and it is here to measure
# rather than to draw: working out where a mark actually paints means resolving
# transforms and the bounds of bezier curves, which is a renderer's job. The
# import is soft so the failure names the package instead of a traceback.
try:
    import svgelements
except ImportError:  # pragma: no cover - the message below is the handling
    svgelements = None

SRC = Path(sys.argv[1] if len(sys.argv) > 1 else
           "C:/Users/JUNKER~1/AppData/Local/Temp/si/node_modules/simple-icons/icons")
OUT = Path(__file__).parent.parent / "web" / "src" / "components" / "brandGlyphs.tsx"

# Our component name -> the Simple Icons slug, with what it is for.
#
# Several are a judgement call and are marked as such: a mark that names the
# right COMPANY but not the exact product is better than no mark, and a mark
# that names a DIFFERENT product is not. Where the second was the only option,
# the entry is left out and the provider shows a generic glyph instead.
MARKS = [
    ("IconGithub", "github", "This project's own repository"),

    # The two self-hosted ones this set carries. OpenCloud is not among them
    # and never wears ownCloud's mark, which would name the wrong project; its
    # own drawing is under LOCAL below.
    ("IconNextcloud", "nextcloud", "Nextcloud"),
    ("IconOwncloud", "owncloud", "ownCloud"),

    ("IconDropbox", "dropbox", "Dropbox"),
    ("IconGooglePhotos", "googlephotos", "Google Photos"),
    ("IconGoogleCloud", "googlecloud", "Google Cloud Storage"),
    ("IconBox", "box", "Box"),
    ("IconMailru", "maildotru", "Mail.ru Cloud"),
    ("IconZoho", "zoho", "Zoho WorkDrive"),
    ("IconSeafile", "seafile", "Seafile"),
    # ShareFile was Citrix's and the mark is still filed under the parent.
    ("IconCitrix", "citrix", "ShareFile, filed under Citrix"),

    # Object storage and infrastructure.
    ("IconBackblaze", "backblaze", "Backblaze B2"),
    ("IconOpenstack", "openstack", "OpenStack Swift"),
    ("IconAkamai", "akamai", "Akamai NetStorage"),
    ("IconHadoop", "apachehadoop", "HDFS"),

    # The S3-compatible field. rclone knows fifty-three of these by name and
    # this app offered one generic entry, so somebody looking for Wasabi or R2
    # found nothing in a list of fifty-one and had to know to pick "S3" and set
    # a field. Each of these is one preset away, exactly as Huawei OBS already
    # was. Three of the twelve have no mark in this set at all - IDrive, Linode
    # and SeaweedFS - and get none rather than a neighbour's.
    ("IconWasabi", "wasabi", "Wasabi"),
    ("IconCloudflare", "cloudflare", "Cloudflare R2"),
    ("IconDigitalOcean", "digitalocean", "DigitalOcean Spaces"),
    ("IconScaleway", "scaleway", "Scaleway Object Storage"),
    ("IconHetzner", "hetzner", "Hetzner Object Storage"),
    ("IconOvh", "ovh", "OVHcloud Object Storage"),
    ("IconSynology", "synology", "Synology C2"),
    ("IconMinio", "minio", "MinIO"),
]

HEAD = '''import type { SVGProps } from 'react'

// ---------------------------------------------------------------------------
// Brand marks. GENERATED by scripts/gen_brand_glyphs.py - do not hand-edit.
//
// Kept apart from `glyphs.tsx` on purpose. That file is one Streamline set,
// drawn on one grid to one convention, which is what makes those icons agree
// with each other. A brand mark cannot come from there: it is somebody else's
// drawing, it must not be redrawn to fit, and it must not be swapped for a
// near neighbour when the set lacks it - a mark naming the WRONG service is
// worse than no mark, which is why several providers here deliberately have
// none.
//
// Source: Simple Icons (simpleicons.org), published under CC0. No attribution
// is required; it is given because knowing where a drawing came from is worth
// more than the licence demands.
//
// TRADEMARKS. Every mark below belongs to its owner. Each is used the one way a
// trademark may be used without permission: to name the thing it refers to. A
// mark appears only on a row that connects to exactly that service, each is
// reproduced unmodified apart from taking `currentColor`, and nothing here
// claims endorsement by or affiliation with any of them.
//
// The design language's other half of this rule: a brand mark is never
// reachable by PATTERN from a translation key. It is passed at the call site
// that means it.
// ---------------------------------------------------------------------------

'''


# ---------------------------------------------------------------------------
# Marks that vanish into the surface they sit on.
#
# "Original und farbig" has one failure mode, and it is not a matter of taste:
# a brand whose logo is navy or black disappears on a dark ground, and one
# whose logo is near-white disappears on a light one. Measured on the running
# app, ShareFile reached a contrast of 1.07 against the dark row and OpenCloud
# 1.09 - which is to say they were there and could not be seen. Making the
# logos bigger made the invisible ones more conspicuously invisible.
#
# jdp: "lass sie flippen. auf dunklem hintergrund sollen sie hell sein, auf
# hellem hintergrund sollen sie so bleiben." So a mark that cannot be read
# against one ground gets a variant for that ground ONLY, keeping its own hue
# and saturation and moving only its lightness. It is the same logo in the same
# colour family, turned up or down until it can be seen, which is what a brand
# guideline does for its own dark backgrounds.
#
# Decided HERE, from the colours themselves, rather than in a hand-kept list of
# names: a list of "these six are too dark" is wrong the moment a mark is added
# or a set changes a hex, and nothing would say so.
SURFACE_DARK = "#393939"   # --carbon-surface2, dark theme: what a row is filled with
SURFACE_LIGHT = "#e8e8e8"  # --carbon-surface2, light theme

# A tile is not one ground, it is three, and measuring only the resting one is
# how eleven marks shipped invisible.
#
# The picker's tile is filled with --carbon-surface2 and lights up under the
# pointer, which in the dark theme means it goes to WHITE. So a mark that sits
# on #393939 at rest sits on #ffffff a moment later, and thirteen values across
# eleven marks fell under the floor against it, eight of them at exactly 1.00 -
# not faint, gone, and gone exactly while somebody was pointing at the thing
# they wanted to read. The
# light theme has the milder half of the same fault: its hover is
# --carbon-surface3 at #d1d1d1, where Cloudflare's orange falls to 1.74.
#
# Two answers, and both are needed. A mark's LIGHT value has to clear the floor
# on every light ground it can land on, which is what this tuple is for. And a
# dark-theme tile that has gone white is showing a light ground, so the mark
# switches to its light value for as long as the pointer is there - see the
# fourth CSS block at the bottom of this file.
GROUNDS_LIGHT = ("#ffffff", SURFACE_LIGHT, "#d1d1d1")

# Below this, the mark is not readable against that ground. The number is where
# the measurement and the eye agree: Dropbox's blue sits at 2.28 and reads
# perfectly well; Filen's black at 1.90 does not.
FLOOR = 2.0
# What a flipped colour has to reach. 4.5 is the text threshold rather than the
# 3.0 for graphics, because a mark this small is closer to a letterform than to
# an illustration.
TARGET = 4.5


# The colour KEYWORDS that turn up in these files, and the reason they are
# handled at all.
#
# put.io's mark writes its light half as `fill="white"`, and every measurement
# in this file looked for a hex or an `rgb(...)` - so that half was invisible to
# the readability check, which then flipped the other half and left this one
# alone. It went unnoticed for as long as the mark carried its own dark plate:
# white on its own plate reads fine, and dropping the plate is what exposed it.
#
# Two keywords rather than the full CSS table on purpose. White and black are
# exactly the two that vanish against one of the two grounds, and anything else
# is refused loudly below rather than passed through - a `fill="navy"` that
# nothing measures is the same defect wearing a different word.
KEYWORDS = {"white": "#ffffff", "black": "#000000"}


def _rgb(colour):
    """`#a00`, `#aa0000`, `rgb(170, 0, 0)` or a known keyword, as 0-255."""
    text = KEYWORDS.get(colour.strip().lower(), colour).strip()
    if text.startswith("rgb"):
        parts = re.findall(r"[\d.]+%?", text)[:3]
        if len(parts) < 3:
            return None
        # `rgb(28.2%,58%,99.6%)` is how a Cairo-exported gradient stop writes
        # itself, and reading those three as 0-255 turns a bright blue into a
        # navy - which is exactly the mistake this whole section exists to
        # catch, so getting it wrong here would flip a mark that reads fine.
        return tuple(
            int(round(float(p[:-1]) * 255 / 100)) if p.endswith("%") else int(float(p))
            for p in parts
        )
    text = text.lstrip("#")
    if len(text) == 3:
        text = "".join(c * 2 for c in text)
    if len(text) != 6:
        return None
    return tuple(int(text[i:i + 2], 16) for i in (0, 2, 4))


def _luminance(rgb):
    def channel(value):
        value /= 255.0
        return value / 12.92 if value <= 0.03928 else ((value + 0.055) / 1.055) ** 2.4
    r, g, b = (channel(v) for v in rgb)
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(one_colour, other):
    a, b = sorted((_luminance(_rgb(one_colour)), _luminance(_rgb(other))), reverse=True)
    return (a + 0.05) / (b + 0.05)


def on_light_grounds(colour):
    """The WORST contrast this colour reaches on any light ground it can sit on.

    The question a mark has to answer is not "can it be read where it rests"
    but "can it be read anywhere it lands", and a tile lands it on three
    different lights: white when a dark-theme tile is hovered, #e8e8e8 at rest
    in the light theme, #d1d1d1 when that one is hovered. A near-white colour
    is worst against white, a dark one worst against #d1d1d1, so neither ground
    alone is the test and the minimum is.
    """
    return min(contrast(colour, ground) for ground in GROUNDS_LIGHT)


def shift(colour, surface, upward, also=()):
    """The same colour, moved along lightness until it can be seen.

    Hue and saturation are untouched: this is the brand's colour at a different
    brightness, not a different colour. Black and white have no hue to keep, so
    they simply become their opposite end, which is what one wants anyway.

    `also` names further (ground, minimum) pairs the result must satisfy on top
    of reaching TARGET on `surface`. It exists because the light theme has two
    grounds rather than one: a colour tuned to 4.5 against the resting
    #e8e8e8 can still sit under the floor against the #d1d1d1 it moves to
    under the pointer, and a mark that vanishes exactly while somebody points
    at it is worse than one that was always faint.
    """
    rgb = _rgb(colour)
    hue, light, sat = colorsys.rgb_to_hls(*(v / 255.0 for v in rgb))
    step = 0.02 if upward else -0.02
    limit = 0.94 if upward else 0.10
    while (light < limit) if upward else (light > limit):
        light += step
        candidate = "#%02x%02x%02x" % tuple(
            round(v * 255) for v in colorsys.hls_to_rgb(hue, min(max(light, 0.0), 1.0), sat)
        )
        if contrast(candidate, surface) >= TARGET and all(
            contrast(candidate, ground) >= minimum for ground, minimum in also
        ):
            return candidate
    return "#%02x%02x%02x" % tuple(
        round(v * 255) for v in colorsys.hls_to_rgb(hue, min(max(light, 0.0), 1.0), sat)
    )


# Every custom property the marks need, in the order they were minted, as
# (name, value on dark, value on light).
VARIABLES = []

# Colours that must follow the theme even though the mark as a whole reads fine.
#
# The readability rule above judges a mark by its BEST colour, which is the
# right question for "can this be seen at all" and the wrong one for a mark
# that is partly white. Most white in a logo is a knockout sitting on the
# brand's own coloured shape - MEGA's M on its red circle, Internxt's X on its
# navy square - and that white must stay white or the logo breaks. White that
# sits directly on the page is the other case, and no measurement here can tell
# the two apart, so this names the one file where it is the second.
#
# Values are (on dark, on light).
FORCE_THEMED = {
    # OpenDrive's logo is drawn for a dark ground: two blue bars and two white
    # ones on a near-black plate. jdp asked for the plate to go ("opendrive logo
    # ohne den dunklen hintergrund"), and without it the two white bars vanish
    # on the light theme. They take the plate's own tone there instead, so the
    # mark keeps its shape and its blue on both grounds. The brand's own
    # light-ground version would be better than this and is worth asking for.
    "opendrive": {"#fff": ("#ffffff", "#2b2b2b")},
    # Uloz.to's asset is white on a #3d3d3d plate. The plate is dropped as a
    # full-bleed rectangle now (see _drop_plate), and the whole mark is that one
    # white - so on a light page it would be white on white, which is not a
    # faint mark but no mark at all. It takes the plate's own tone there, the
    # same trade OpenDrive makes above, and the brand's light-ground version
    # would be better than either and is worth asking for.
    "ulozto": {"#fff": ("#ffffff", "#3d3d3d")},
}


def _drop_plate(root, source, slug):
    """Remove the rectangle the rest of the mark is sitting ON.

    A brand's own asset is often drawn on its plate: a rectangle in the brand's
    dark, with the mark in white on top. That is right for a press kit and
    wrong in a list of fifty logos, where every OTHER mark sits on the page and
    this one arrives in its own box. jdp reported it twice, about two different
    files - "opendrive logo ohne den dunklen hintergrund" and, of Uloz.to, "hat
    noch ein hintergrund".

    Measured rather than listed by name, because a list of names only ever
    contains the files somebody has already complained about.

    A plate is defined here by CONTAINMENT: the first thing drawn is a
    rectangle, and everything else drawn fits inside it. That is what a plate
    is, and it is a better definition than the one this had first, which asked
    whether the rectangle filled the CANVAS. Linkbox is why: its file is a
    367x70 wordmark canvas whose text was lost on export, so the plate covers
    the symbol block and about a fifth of the canvas - not full-bleed by any
    measure, and a plate to anybody looking at it.

    What it does NOT do is guess about colour. Dropping the plate can leave a
    white mark invisible on a light page, and the answer to that is FORCE_THEMED
    above, which says so per file and in as many words.
    """
    if svgelements is None:
        raise SystemExit("the plate rule needs svgelements (pip install svgelements)")
    try:
        drawing = svgelements.SVG.parse(str(source))
    except Exception:
        return

    boxes = []
    for element in drawing.elements():
        if not isinstance(element, svgelements.Shape):
            continue
        try:
            bounds = element.bbox()
        except Exception:
            continue
        if bounds:
            boxes.append((type(element).__name__, bounds))
    if len(boxes) < 2 or boxes[0][0] != "Rect":
        return

    plate = boxes[0][1]
    rest = boxes[1:]
    # Half a unit of tolerance: these come out of drawing programs, and a plate
    # a rounding short of covering the mark is still the mark's plate.
    covers = (
        plate[0] <= min(b[0] for _, b in rest) + 0.5
        and plate[1] <= min(b[1] for _, b in rest) + 0.5
        and plate[2] >= max(b[2] for _, b in rest) - 0.5
        and plate[3] >= max(b[3] for _, b in rest) - 0.5
    )
    if not covers:
        return

    parents = {child: parent for parent in root.iter() for child in parent}
    for el in root.iter():
        if el.tag == SVG_NS + "rect":
            parents[el].remove(el)
            print("  %s: dropped the plate it was sitting on (%gx%g)"
                  % (slug, plate[2] - plate[0], plate[3] - plate[1]))
            return


def themed(colours, slug):
    """Which of these colours need a per-theme variant, and under what names.

    Returns a map from the colour AS WRITTEN in the file to the `var(...)` that
    replaces it, empty when the mark reads fine on both grounds.

    Judged per MARK rather than per colour: a two-tone logo with one readable
    half would come out half flipped and half not, which is no longer the logo.
    """
    usable = [c for c in colours if _rgb(c)]
    if not usable:
        return {}

    # The named exceptions first: a colour listed here follows the theme
    # whatever the measurement says about the mark as a whole.
    forced = {}
    for colour, (on_dark, on_light) in FORCE_THEMED.get(slug, {}).items():
        if colour not in usable:
            raise SystemExit("FORCE_THEMED names %s in %s, which does not paint with it" % (colour, slug))
        # A hand-given pair skips the measurement that mints every other value,
        # so it gets the measurement here instead. Without this, the one place
        # in the file where a human picks the hex is the one place a hex can be
        # too faint to see and nothing says so.
        if contrast(on_dark, SURFACE_DARK) < FLOOR or on_light_grounds(on_light) < FLOOR:
            raise SystemExit(
                "FORCE_THEMED %s/%s is too faint: %.2f on the dark ground, %.2f on the "
                "worst light one" % (slug, colour, contrast(on_dark, SURFACE_DARK),
                                     on_light_grounds(on_light))
            )
        name = "--brand-%s-forced%d" % (slug, len(forced))
        VARIABLES.append((name, _hex(on_dark), _hex(on_light)))
        forced[colour] = "var(%s)" % name

    # Naming one colour by hand settles THAT colour, not the mark. Returning
    # here was a real hole: OpenDrive's white bars are forced, its blue ones
    # are not, and the blue was never measured at all - it sat at 1.74 against
    # the light theme's hover for as long as the exception existed. So the rest
    # of the mark goes through the same measurement as any other.
    rest = [c for c in usable if c not in forced]
    if not rest:
        return forced

    dark_best = max(contrast(c, SURFACE_DARK) for c in rest)
    light_best = max(on_light_grounds(c) for c in rest)
    if dark_best >= FLOOR and light_best >= FLOOR:
        return forced
    if dark_best < FLOOR and light_best < FLOOR:
        raise SystemExit(
            "%s cannot be read on either ground (%.2f dark, %.2f light): it needs a "
            "different source file, not a lightness shift" % (slug, dark_best, light_best)
        )
    swap = dict(forced)
    minted = {}
    for colour in rest:
        # Keyed by what the colour IS, not by how it was spelt: one file writes
        # the same navy as `#20434F` and `#20434f`, and two properties for one
        # colour is two things to keep in step for no reason.
        key = _rgb(colour)
        if key not in minted:
            name = "--brand-%s-%d" % (slug, len(minted))
            on_dark = shift(colour, SURFACE_DARK, upward=True) if dark_best < FLOOR else colour
            on_light = (
                shift(colour, SURFACE_LIGHT, upward=False,
                      also=[(ground, FLOOR) for ground in GROUNDS_LIGHT])
                if light_best < FLOOR
                else colour
            )
            VARIABLES.append((name, _hex(on_dark), _hex(on_light)))
            minted[key] = name
        swap[colour] = "var(%s)" % minted[key]
    return swap


def _hex(colour):
    """A colour as a hex string, whatever it was written as on the way in.

    Only the OUTPUT is normalised. A keyword is a perfectly good thing to find
    in somebody else's file, and a perfectly bad thing to emit: the CSS these
    variables land in is read back by the contrast guard on the other side of
    the repo, which parses hex and returns nothing for a word. That guard fell
    over on `--brand-putio-0: white` the moment the keyword became reachable -
    a blind spot answering a blind spot.
    """
    text = KEYWORDS.get(str(colour).strip().lower())
    return text or colour


def apply_swap(source, swap):
    """Put the custom properties where the literal colours were.

    Everywhere the mark PAINTS, and nowhere else. A `<mask>` block is left
    alone for the same reason its colours were never measured: white there
    means "show all of this" rather than "draw in white", and a theme variable
    in its place would make the mark's own visibility follow the theme - a
    logo that fades instead of a logo that flips.
    """
    masks = []

    def park(match):
        masks.append(match.group(0))
        return "\0mask%d\0" % (len(masks) - 1)

    source = re.sub(r"<mask\b.*?</mask>", park, source, flags=re.S)
    for colour, variable in swap.items():
        source = source.replace('"%s"' % colour, '"%s"' % variable)
    for index, block in enumerate(masks):
        source = source.replace("\0mask%d\0" % index, block)
    return source


# The brands' own colours, keyed by slug, from the set's own data file.
COLOURS = {}
_data = SRC.parent / "data" / "simple-icons.json"
if _data.exists():
    import json

    _raw = json.loads(io.open(_data, encoding="utf-8").read())
    for entry in (_raw["icons"] if isinstance(_raw, dict) else _raw):
        title = entry.get("title", "")
        # The slug is the title lowercased with everything but letters and
        # digits removed, which is the set's own rule; a `slug` field overrides
        # it where the two differ.
        s_ = entry.get("slug") or re.sub(r"[^a-z0-9]", "", title.lower())
        COLOURS[s_] = "#" + entry["hex"]


def one(name: str, slug: str, note: str) -> str:
    svg = io.open(SRC / (slug + ".svg"), encoding="utf-8").read()
    box = re.search(r'viewBox="([^"]+)"', svg)
    paths = re.findall(r'<path d="([^"]+)"', svg)
    if not box or not paths:
        raise SystemExit("cannot read %s.svg" % slug)
    colour = COLOURS.get(slug)
    if not colour:
        raise SystemExit("no brand colour for %s: the data file did not carry it" % slug)
    body = "\n".join('      <path d="%s" />' % d for d in paths)
    # The brand's OWN colour rather than currentColor, because a logo drawn in
    # the interface's ink is not the logo, it is a silhouette of it. jdp: "die
    # logos sollen original und farbig sein."
    #
    # Simple Icons draws every mark as one path in one colour, and for most of
    # these that IS the real thing: Dropbox's mark is one blue, Nextcloud's one
    # blue, MEGA's one red. For the few whose official mark is multi-coloured -
    # Google Drive - it is that brand's primary colour rather than its full
    # drawing, which is as close as a CC0 set gets and much closer than grey.
    #
    # `fill` sits on the svg rather than on each path, so one style on the
    # element can still override the whole mark where a surface demands it.
    swap = themed([colour], slug)
    painted = swap.get(colour, colour)
    aside = "" if not swap else ", flipped for the ground it cannot be read on"
    # The source's own box. Tightening onto the drawing happens later, in
    # crop_to_ink, off the finished markup.
    cropped = box.group(1)
    return f'''/** {note}. Simple Icons: {slug}, in its own {colour}{aside} */
export function {name}(props: SVGProps<SVGSVGElement>) {{
  return (
    <svg viewBox="{cropped}" width="1em" height="1em" fill="{painted}" aria-hidden {{...props}}>
{body}
    </svg>
  )
}}
'''


# Marks Simple Icons does not carry, kept as their own SVG under
# scripts/brand-paths/. Each is somebody else's file, reproduced unmodified,
# with its source and its licence recorded here and in that folder's README.
#
# Same trademark reasoning as everything above: used to name the thing it refers
# to, reproduced unmodified, no claim of endorsement. What differs is the
# licence position - these are not CC0 - so each entry carries the licence it
# arrived under, and every one of those licences is satisfied by naming it.
# Where jdp's files came from, and the licence position they arrive under.
#
# Not an icon set: each is the brand's OWN drawing, collected by hand. That
# beats a CC0 set twice over - it is the real logo rather than a one-colour
# silhouette of it, and several of these exist in no set at all. The licence is
# each owner's, and the use is the one a trademark needs no permission for:
# naming the thing it refers to, on a row that connects to exactly that thing.
JDP = "supplied by jdp, from the brand's own material"
BRAND = "the brand's own mark"

LOCAL = [
    # jdp: "alle fehlenden logos liegen auf dem Desktop. auch bestehende
    # aktualisieren wenn eines auf dem desktop liegt."
    #
    # A `-dark`/`-light` PAIR is the same drawing in two inks: `-dark` is the
    # dark ink for a light ground, `-light` the white one for a dark ground.
    # Detected by the files themselves, and where a pair exists it is used
    # INSTEAD of the computed lightness shift, because the brand's own second
    # drawing beats anything this file can calculate.

    # The thirteen that had no mark at all.
    ("IconPcloud", "pcloud", "pCloud", JDP, BRAND),
    ("IconKoofr", "koofr", "Koofr", JDP, BRAND),
    ("IconJottacloud", "jottacloud", "Jottacloud", JDP, BRAND),
    ("IconOpendrive", "opendrive", "OpenDrive", JDP, BRAND),
    ("IconPutio", "putio", "put.io", JDP, BRAND),
    ("IconSugarsync", "sugarsync", "SugarSync", JDP, BRAND),
    ("IconPikpak", "pikpak", "PikPak", JDP, BRAND),
    ("IconInternxt", "internxt", "Internxt", JDP, BRAND),
    ("IconUlozto", "ulozto", "Ulož.to", JDP, BRAND),

    # The three the S3 round left without a mark. Not from Simple Icons, which
    # carries none of them: Linode and IDrive come from the dashboard-icons set
    # this repo already uses under Apache 2.0, and SeaweedFS from the project's
    # own repository - an open project's own icon, which is the most honest
    # source there is for one.
    ("IconLinode", "linode", "Linode Object Storage", JDP, BRAND),
    ("IconIdrive", "idrive", "IDrive e2", JDP, BRAND),
    ("IconSeaweedfs", "seaweedfs", "SeaweedFS", JDP, BRAND),

    # The two the provider sweep added and left markless. Ceph is jdp's file;
    # Garage comes from the project's own icon, by way of jdp's container
    # repository for it - the same source SeaweedFS uses, and the most honest
    # one there is for an open project's mark.
    ("IconCeph", "ceph", "Ceph", JDP, BRAND),
    ("IconGarage", "garage", "Garage",
     "the Garage project's own icon, via junkerderprovinz/garage", BRAND),
    ("IconQuatrix", "quatrix", "Quatrix", JDP, BRAND),
    ("IconLinkbox", "linkbox", "Linkbox", JDP, BRAND),
    ("IconGofile", "gofile", "Gofile", JDP, BRAND),
    ("IconPixeldrain", "pixeldrain", "Pixeldrain", JDP, BRAND),

    # Marks that used to come from an icon set and now come from the brand.
    ("IconAzure", "azureblob", "Azure Blob Storage, under Azure's own mark", JDP, BRAND),
    ("IconFilen", "filen", "Filen", JDP, BRAND),
    ("IconFilesCom", "filescom", "Files.com", JDP, BRAND),
    ("IconGoogleDrive", "gdrive", "Google Drive", JDP, BRAND),
    ("IconHuaweiCloud", "huaweicloud", "Huawei Cloud OBS", JDP, BRAND),
    ("IconICloud", "icloud", "iCloud Drive", JDP, BRAND),
    ("IconIonos", "hidrive", "IONOS HiDrive", JDP, BRAND),
    ("IconMega", "mega", "MEGA", JDP, BRAND),
    ("IconProtonDrive", "protondrive", "Proton Drive", JDP, BRAND),
    ("IconStorj", "storj", "Storj", JDP, BRAND),
    ("IconYandex", "yandex", "Yandex Disk, under Yandex Cloud's mark", JDP, BRAND),

    # Pairs: one drawing, two inks, picked by theme.
    ("IconCloudinary", "cloudinary", "Cloudinary", JDP, BRAND),
    ("IconInternetArchive", "internetarchive", "Internet Archive", JDP, BRAND),
    ("IconOpencloud", "opencloud", "OpenCloud", JDP, BRAND),

    # Dashboard Icons, Apache-2.0, for the three nobody has supplied.
    ("IconOnedrive", "microsoft-onedrive", "OneDrive",
     "homarr-labs/dashboard-icons, svg/microsoft-onedrive.svg", "Apache-2.0"),
    ("IconOracleCloud", "oracle-cloud", "Oracle Object Storage, part of Oracle Cloud",
     "homarr-labs/dashboard-icons, svg/oracle-cloud.svg", "Apache-2.0"),
]

# Attributes that mean nothing inside a component, or that the wrapper sets.
DROP_ROOT = {"xmlns", "version", "width", "height", "id", "class"}

# SVG attribute -> its JSX spelling, where lowercasing the hyphen is not the
# rule. Everything else hyphenated is camelCased below.
SPECIAL = {"class": "className", "for": "htmlFor"}


def _camel(name):
    """`stop-color` -> `stopColor`, but `data-x` and `aria-x` stay put."""
    if name.startswith("data-") or name.startswith("aria-"):
        return name
    if name in SPECIAL:
        return SPECIAL[name]
    head, _, tail = name.partition("-")
    while tail:
        piece, _, rest = tail.partition("-")
        head += piece[:1].upper() + piece[1:]
        tail = rest
    return head


def _style_object(value):
    """`fill:#a00;fill-opacity:1` -> a JSX style object.

    JSX takes an object here, never the CSS string an SVG file carries, and
    several of these marks put their whole colour in a `style` attribute.
    """
    pairs = []
    for chunk in value.split(";"):
        key, sep, val = chunk.partition(":")
        if not sep or not key.strip():
            continue
        pairs.append("%s: %s" % (_camel(key.strip()), json.dumps(val.strip())))
    return "{{ %s }}" % ", ".join(pairs) if pairs else None


def _jsx(node, ids, slug, depth):
    """One SVG element and its children as JSX source, or None to skip it."""
    tag = node.tag.split("}")[-1]
    # <title> and <desc> go, whatever they hold. What they hold is the asset
    # name from whoever drew the file ("Icon-storage-86"), which labels nothing
    # a reader of this interface would want read out, and the wrapper is
    # aria-hidden regardless: the provider's NAME sits next to the mark.
    if tag in ("title", "desc"):
        return None
    pad = "  " * depth
    attrs = []
    for raw, value in node.attrib.items():
        # `xlink:href` arrives fully qualified and is `xlinkHref` in JSX.
        if raw.startswith("{http://www.w3.org/1999/xlink}"):
            key = "xlinkHref"
        elif raw.startswith("{"):
            continue  # any other foreign namespace means nothing to the DOM here
        else:
            key = _camel(raw)
        if key in ("xmlns", "xmlnsXlink", "version"):
            continue
        # Every id in the file is rewritten, because two marks on one page that
        # both define `radial0` would collide: `url(#radial0)` resolves to
        # whichever came first in the document, so one logo would wear the
        # other's gradient. Prefixing with the slug makes each file's ids its
        # own.
        if key == "id":
            value = ids[value]
        else:
            for old, new in ids.items():
                value = value.replace("url(#%s)" % old, "url(#%s)" % new)
                if value == "#" + old:
                    value = "#" + new
        if key == "style":
            obj = _style_object(value)
            if not obj:
                continue
            attrs.append("style=%s" % obj)
            continue
        attrs.append("%s=%s" % (key, '"%s"' % value if '"' not in value else "{%s}" % json.dumps(value)))
    head = ("<%s " % tag) + " ".join(attrs) if attrs else "<%s" % tag
    # Text would be silently swallowed otherwise, which is how an <title> full
    # of somebody's asset name came through this generator as an empty tag.
    # Nothing among these marks draws with <text>; if one ever does, it should
    # stop the build rather than lose its lettering.
    if (node.text or "").strip():
        raise SystemExit("brand-paths/%s.svg: <%s> carries text this generator drops" % (slug, tag))

    kids = [c for c in (_jsx(k, ids, slug, depth + 1) for k in node) if c]
    if not kids:
        return "%s%s />" % (pad, head)
    return "%s%s>\n%s\n%s</%s>" % (pad, head, "\n".join(kids), pad, tag)


BRAND_DIR = Path(__file__).parent / "brand-paths"

SVG_NS = "{http://www.w3.org/2000/svg}"

# Every mark's own INK, measured, for marks whose drawing does not fill the box
# it was saved in.
#
# The eye compares a glyph's ink, not its viewBox, and imported artwork varies
# wildly in how much of its own box it uses: measured across the running list,
# the painted extent ran from 32px to 64px, a factor of two, on marks that are
# all in identically sized boxes. jdp, looking at it: "die logos sind stark
# unterschiedlich gross." Cropping the box to the drawing is what makes them
# agree, and it is the same fix the sibling app arrived at after five rounds of
# the same report.
#
# A second thing it fixes: a logo exported with its wordmark as live TEXT loses
# the text and keeps the box, so the symbol ends up in a corner of a mostly
# empty rectangle. Linkbox looked like a 5.3:1 wordmark 8 pixels tall and its
# ink is square.
#
# NO LONGER HAND-KEPT. This used to be a table of boxes read off getBBox() in
# the running app, and it had the defect every such table has: it was right for
# the marks somebody had looked at and silent about the rest. Synology sat in a
# box 3.90 times taller than its own drawing for as long as the list existed,
# which is why a wordmark that fills its line rendered six pixels tall. Nobody
# was going to notice by reading a list of twenty-eight names.
#
# `crop_to_ink` below now measures every mark instead, off the FINAL markup -
# after the plate is dropped, after the styles are folded in - and the
# measurement reproduced twenty-six of these boxes to the last decimal, which
# is what earned it the job. The dict stays as an OVERRIDE for a mark the
# measurement gets wrong, and `crop_to_ink` refuses an entry that merely
# restates what it measured: a hand value that agrees with the measurement is
# not a safety net, it is a second copy to keep in step.
#
# It no longer feeds the emitted box or the plate rule. It used to do both, and
# that coupling was a trap: the plate rule recognises a rectangle by it being
# full-bleed, so handing it a box already cropped to the ink makes every plate
# invisible to it. Both now read the SOURCE canvas and the cropping happens
# afterwards, on the finished markup.
# EMPTY, and that is the result rather than an omission. Twenty-eight entries
# stood here; the measurement reproduced twenty-six of them to the last
# decimal, and the two it disagreed with - OpenDrive and Linkbox - were not
# measured boxes at all but the source file's own loose rectangle. Linkbox's
# said 68.4 wide where the drawing is 34.7, which is the very defect this table
# was written to fix, sitting inside the fix.
INK = {}

# How much of its box a mark may waste before it is cropped. Two percent is
# below what any eye resolves and above the rounding in these files, so it
# separates "this box is the drawing" from "this box has room in it".
SLACK = 1.02

# Overrides the measurement makes unnecessary, collected across the whole run
# and refused together at the end. One at a time would mean twenty-eight runs
# to clear twenty-eight entries.
REDUNDANT = []


def _measure_ink(component, name):
    """The box the mark actually PAINTS in, in its own viewBox units.

    Measured off the finished markup rather than the source file, because by
    this point three things have already changed the drawing: a full-bleed
    plate may have been dropped, an Illustrator `<style>` block has been folded
    into the elements, and the ids have been prefixed. Measuring earlier would
    describe a mark nobody ships.

    `<defs>`, `<mask>` and `<clipPath>` are cut out first, for the same reason
    their colours are not counted as ink: what is in them is a recipe, not a
    drawing, and a full-canvas mask rectangle would report the whole box as
    painted - which is exactly what Quatrix carries two of.
    """
    if svgelements is None:
        raise SystemExit(
            "crop_to_ink needs the svgelements package (pip install svgelements).\n"
            "It is what measures where each mark actually paints; without it the\n"
            "boxes would go back to being a hand-kept list."
        )
    markup = component[component.index("<svg"):component.rindex("</svg>") + 6]
    markup = markup.replace(" aria-hidden {...props}", " ").replace("{...props}", " ")

    # JSX spellings back to SVG's own. Only the ones these files carry: an
    # unknown attribute would be ignored by the parser and could take a whole
    # shape's geometry with it.
    def style(match):
        pairs = re.findall(r'(\w+):\s*"([^"]*)"', match.group(1))
        return 'style="%s"' % ";".join(
            "%s:%s" % (re.sub(r"(?<!^)(?=[A-Z])", "-", key).lower(), value)
            for key, value in pairs
        )

    markup = re.sub(r"style=\{\{([^}]*)\}\}", style, markup)
    for jsx, svg in (
        ("fillRule", "fill-rule"), ("fillOpacity", "fill-opacity"),
        ("clipPath", "clip-path"), ("clipRule", "clip-rule"),
        ("strokeWidth", "stroke-width"), ("strokeLinecap", "stroke-linecap"),
        ("strokeLinejoin", "stroke-linejoin"), ("strokeMiterlimit", "stroke-miterlimit"),
        ("stopColor", "stop-color"), ("stopOpacity", "stop-opacity"),
        ("xlinkHref", "xlink:href"), ("fillOpacity", "fill-opacity"),
    ):
        markup = markup.replace(jsx + "=", svg + "=")
    for tag in ("defs", "mask", "clipPath"):
        markup = re.sub(r"<%s\b.*?</%s>" % (tag, tag), "", markup, flags=re.S)

    box = [float(v) for v in re.search(r'viewBox="([^"]+)"', markup).group(1).replace(",", " ").split()]
    # `width="1em"` is what the interface wants and what the parser cannot
    # resolve - it raises rather than guessing. Handing it the viewBox's own
    # size makes the viewport transform the identity, so the numbers that come
    # back are already in the units the box is written in.
    markup = re.sub(r'\swidth="[^"]*"', "", markup, count=1)
    markup = re.sub(r'\sheight="[^"]*"', "", markup, count=1)
    markup = markup.replace(
        "<svg ",
        '<svg xmlns="http://www.w3.org/2000/svg" width="%g" height="%g" ' % (box[2], box[3]),
        1,
    )

    handle, path = tempfile.mkstemp(suffix=".svg")
    os.close(handle)
    try:
        io.open(path, "w", encoding="utf-8").write(markup)
        drawing = svgelements.SVG.parse(path)
    finally:
        os.unlink(path)

    left = top = float("inf")
    right = bottom = float("-inf")
    for element in drawing.elements():
        if not isinstance(element, svgelements.Shape):
            continue
        try:
            # WITH the stroke, and that word is the whole difference for a mark
            # drawn as an outline. Oracle Cloud is a stadium in `fill="none"`
            # with a 4-unit stroke: the path runs 2..30 across a 32-wide
            # canvas, and the two units either side ARE the drawing. Measuring
            # the path alone cropped the box onto the centreline and sliced
            # half the outline off all four edges. jdp: "das oracle logo passt
            # nicht."
            bounds = element.bbox(with_stroke=True)
        except Exception:
            continue
        if not bounds:
            continue
        left, top = min(left, bounds[0]), min(top, bounds[1])
        right, bottom = max(right, bounds[2]), max(bottom, bounds[3])
    if right <= left or bottom <= top:
        raise SystemExit("%s paints nothing this can measure" % name)
    # Back into the box's own coordinates: the parse put its origin at 0,0.
    return box, (left + box[0], top + box[1], right - left, bottom - top)


def crop_to_ink(component, name):
    """Tighten a mark's viewBox onto its drawing.

    The eye compares a glyph's INK, not its viewBox, and a tile scales a mark
    to fit - so a drawing in a box twice its height arrives at half the size of
    its neighbours, having asked for the same space and used a quarter of it.
    """
    declared, ink = _measure_ink(component, name)
    slack_x = declared[2] / ink[2]
    slack_y = declared[3] / ink[3]
    # `or 0.0` collapses a measured -0.0 onto 0, because -0.0 is falsy: a
    # bezier that touches the axis lands either side of zero depending on
    # rounding, and "-0" in a viewBox is a diff nobody caused.
    tight = "%s %s %s %s" % tuple(
        (("%.2f" % (round(value, 2) or 0.0)).rstrip("0").rstrip(".") or "0") for value in ink
    )

    if name in INK:
        # An override that agrees with the measurement is dead weight, and dead
        # weight in a table like this is what makes the next person believe the
        # table is doing the work.
        if slack_x <= SLACK and slack_y <= SLACK:
            REDUNDANT.append((name, INK[name], tight))
        else:
            # An override that DISAGREES is the one worth keeping, and worth
            # saying out loud: it is a decision somebody made against the
            # measurement, and silence would make it look like agreement.
            print("  %s: kept its override %s over the measured %s"
                  % (name, INK[name], tight))
        return component

    if slack_x <= SLACK and slack_y <= SLACK:
        return component
    print("  %s: cropped to its ink (%.2fx wide, %.2fx tall)" % (name, slack_x, slack_y))
    cropped, hits = re.subn(r'viewBox="[^"]*"', 'viewBox="%s"' % tight, component, count=1)
    # A replacement that does not land is the worst outcome here, because the
    # line above has already announced the crop: the report would say the mark
    # was fixed and the file would carry the old box. Matching the viewBox by
    # pattern rather than by rebuilding its text avoids the whole class - the
    # numbers come back out of a float and would not round-trip.
    if hits != 1:
        raise SystemExit("%s: could not find its viewBox to crop" % name)
    return cropped


def _inline_css(root, slug):
    """Fold an Illustrator `<style>` block into the elements it paints.

    These files carry their colours as `.st0 { fill: … }` rules in a `<style>`
    element. Keeping that would be the id-collision bug again and worse: class
    names are GLOBAL to the document, so two marks both defining `.st0` would
    have one wearing the other's fill, and unlike ids there is nothing local
    about them to prefix away safely. Dissolving the rules into the elements
    makes each component self-contained, which is what a component should be.

    Runs before the JSX pass on purpose, so a `url(#…)` inside a rule is
    renamed by the same id-prefixing as every other reference.
    """
    parents = {child: parent for parent in root.iter() for child in parent}
    rules = {}
    for style in [e for e in root.iter() if e.tag == SVG_NS + "style"]:
        text = re.sub(r"/\*.*?\*/", "", style.text or "", flags=re.S)
        for selector, body in re.findall(r"([^{}]+)\{([^{}]*)\}", text):
            for one_selector in selector.split(","):
                one_selector = one_selector.strip()
                if not re.fullmatch(r"\.[-\w]+", one_selector):
                    raise SystemExit(
                        "brand-paths/%s: <style> carries the selector %r, which this "
                        "generator only handles as a plain class" % (slug, one_selector)
                    )
                rules.setdefault(one_selector[1:], []).append(body.strip().strip(";"))
        parents[style].remove(style)

    for el in root.iter():
        names = (el.get("class") or "").split()
        if not names:
            continue
        del el.attrib["class"]
        # The element's own `style` wins, so it goes last.
        declarations = [d for n in names for d in rules.get(n, [])]
        if el.get("style"):
            declarations.append(el.get("style").strip().strip(";"))
        if declarations:
            el.set("style", "; ".join(declarations))
    return root


def _single_ink(path, slug):
    """The one colour a monochrome file paints with, black when it names none.

    Refuses anything with a second colour: a pair is only two INKS of one
    drawing, and a two-colour half would come out of this as a mark repainted
    in somebody else's idea of its colour.
    """
    text = io.open(path, encoding="utf-8").read()
    colours = {c.lower() for c in re.findall(r"#[0-9a-fA-F]{3,6}", text)}
    if len(colours) > 1:
        raise SystemExit("%s paints in %d colours; a pair half must be one ink" % (path.name, len(colours)))
    if not colours:
        return "#000000"  # no fill named anywhere: SVG's own default
    ink = colours.pop()
    return "#" + "".join(c * 2 for c in ink[1:]) if len(ink) == 4 else ink


def pair(name, slug, note, source, licence):
    """One drawing supplied in two inks, picked by theme rather than computed.

    `-dark` is the dark ink, for a light ground; `-light` the white one, for a
    dark ground. Where a brand has drawn both, that beats the lightness shift
    further up this file every time: the shift is this generator's guess at
    what a lighter version of a colour should be, and these are what the owner
    actually drew.
    """
    dark_file = BRAND_DIR / (slug + "-dark.svg")
    light_file = BRAND_DIR / (slug + "-light.svg")
    dark_ink = _single_ink(dark_file, slug)
    light_ink = _single_ink(light_file, slug)

    # The two files must be the same drawing. If they are not, one component
    # cannot serve both and saying so beats shipping whichever happened to be
    # parsed first.
    geometry = [re.findall(r'\sd="([^"]+)"', io.open(f, encoding="utf-8").read()) for f in (dark_file, light_file)]
    if geometry[0] != geometry[1] or not geometry[0]:
        raise SystemExit("%s: the two inks are not the same drawing" % slug)

    root = _inline_css(ET.fromstring(io.open(dark_file, encoding="utf-8").read()), slug)
    box = root.get("viewBox")
    if not box:
        raise SystemExit("brand-paths/%s-dark.svg has no viewBox" % slug)

    variable = "--brand-%s-0" % slug
    VARIABLES.append((variable, light_ink, dark_ink))

    # Every shape loses its own fill and takes the property from the root, which
    # is what makes one geometry answer to both inks.
    ids = {}
    body = "\n".join(c for c in (_jsx(k, ids, slug, 3) for k in root) if c)
    body = re.sub(r'\s+fill="[^"]*"', "", body)

    return f'''/** {note}. Source: {source} ({licence}), in both its inks */
export function {name}(props: SVGProps<SVGSVGElement>) {{
  return (
    <svg viewBox="{box}" width="1em" height="1em" fill="var({variable})" aria-hidden {{...props}}>
{body}
    </svg>
  )
}}
'''


def local(name, slug, note, source, licence):
    # A brand that supplied both of its inks is drawn from the pair instead.
    if not (BRAND_DIR / (slug + ".svg")).is_file():
        return pair(name, slug, note, source, licence)
    path = BRAND_DIR / (slug + ".svg")
    root = _inline_css(ET.fromstring(io.open(path, encoding="utf-8").read()), slug)

    # The SOURCE's box: its own if it has one, otherwise built from width and
    # height. Several of these carry only a size, and a component with no
    # viewBox does not scale to the 1em the interface asks for.
    #
    # The source's rather than a tightened one, because the plate rule below
    # measures a candidate rectangle against THIS: a plate is full-bleed by
    # definition, so it can only be recognised against the canvas it bleeds to.
    # Handing it a box already cropped to the ink made it miss Linkbox's plate
    # entirely, which then came back into the mark as a coloured square.
    box = root.get("viewBox")
    if not box:
        w, h = root.get("width"), root.get("height")
        if not w or not h:
            raise SystemExit("brand-paths/%s.svg has neither viewBox nor size" % slug)
        box = "0 0 %s %s" % (w, h)

    _drop_plate(root, path, slug)

    ids = {}
    for el in root.iter():
        if el.get("id"):
            ids[el.get("id")] = "%s-%s" % (slug, el.get("id"))

    kids = [c for c in (_jsx(k, ids, slug, 3) for k in root) if c]
    if not kids:
        raise SystemExit("brand-paths/%s.svg is empty" % slug)
    body = "\n".join(kids)

    # The ROOT's own painting attributes come along. Dropping them was a real
    # defect: Yandex's file carries its whole colour as `fill` on the `<svg>`
    # and nowhere else, so the mark came out black - and then read as a mark
    # that simply has no colour rather than as one this generator threw away.
    skip = {"viewBox", "width", "height", "id", "class", "role", "style", "x", "y"}
    root_attrs = []
    for raw, value in root.attrib.items():
        if raw.startswith("{") or raw in skip or _camel(raw) in ("xmlns", "xmlnsXlink", "version"):
            continue
        root_attrs.append('%s="%s"' % (_camel(raw), value))

    # A file that names no colour ANYWHERE paints in SVG's default, which is
    # black - and black is exactly what disappears on a dark ground. Saying so
    # explicitly is what lets the readability check below see it at all;
    # Pixeldrain's mark is one such file and was invisible because of it.
    # What the mark PAINTS with, which is not everything that names a colour.
    #
    # A `<mask>` is drawn in white to mean "show all of this" and in black to
    # mean "hide it"; neither is ink, and neither is on screen. Quatrix's file
    # carries two such masks, so the readability check saw a white it would
    # never draw, called the mark readable on a dark ground on the strength of
    # it, and left the orange that IS drawn at 1.74 against the light theme's
    # hover. Worse, had the mark been flipped, the shift would have moved the
    # mask's white along with everything else - and a mask painted in grey
    # shows the drawing at grey's opacity, which is a logo fading out rather
    # than a logo changing colour.
    painted_text = re.sub(r"<mask\b.*?</mask>", " ", body, flags=re.S) + " " + " ".join(root_attrs)
    found = re.findall(
        r'"(#[0-9a-fA-F]{3,8}|rgb\([^"]*\)|%s)"' % "|".join(KEYWORDS),
        painted_text,
    )

    # Any OTHER word where a colour belongs is refused rather than rendered.
    # A value nothing here can measure is a value the readability check silently
    # skips, and the mark then ships half-flipped - which is exactly what put.io
    # did with `fill="white"` for as long as its own plate hid the consequence.
    for attribute in ("fill", "stroke"):
        for value in re.findall(r'%s="([^"]*)"' % attribute, painted_text):
            if value in ("none", "currentColor", "transparent") or value.startswith("var(") \
                    or value.startswith("url(") or value.startswith("#") \
                    or value.startswith("rgb") or value.lower() in KEYWORDS:
                continue
            raise SystemExit(
                "%s paints with %s=\"%s\", which nothing here can measure. Add it to "
                "KEYWORDS with its hex, or give the file a real colour." % (slug, attribute, value)
            )
    if not found:
        root_attrs.append('fill="#000000"')
        found = ["#000000"]

    swap = themed(found, slug)
    body = apply_swap(body, swap)
    root_attrs = [apply_swap(a, swap) for a in root_attrs]
    painted = ("".join(" " + a for a in root_attrs))

    # Whatever the file paints WITH stays: `fill`, `style`, gradients, groups
    # and all. A mark drawn in several tones is several tones, and flattening
    # one to a single ink would be redrawing somebody's logo.
    return f'''/** {note}. Source: {source} ({licence}) */
export function {name}(props: SVGProps<SVGSVGElement>) {{
  return (
    <svg viewBox="{box}"{painted} width="1em" height="1em" aria-hidden {{...props}}>
{body}
    </svg>
  )
}}
'''


CSS_OUT = Path(__file__).parent.parent / "web" / "src" / "brandGlyphs.css"

CSS_HEAD = """/* Brand marks that need a different lightness on one of the two grounds.
   GENERATED by scripts/gen_brand_glyphs.py - do not hand-edit.

   A logo drawn in navy or in black is invisible on a dark surface, and one
   drawn in near-white is invisible on a light one. Measured on the running
   app: ShareFile reached a contrast of 1.07 against the dark row, OpenCloud
   1.09. They were there and could not be seen.

   So a mark that fails on one ground carries its own colour as a custom
   property, and that property holds a shifted LIGHTNESS on that ground only -
   same hue, same saturation, same logo. jdp: "lass sie flippen. auf dunklem
   hintergrund sollen sie hell sein, auf hellem hintergrund sollen sie so
   bleiben."

   Which marks appear here is decided by measurement in the generator, not by a
   hand-kept list of names: such a list is wrong the moment a mark is added or
   a set changes a hex, and nothing would say so.

   The first three blocks mirror tokens.css exactly, so the marks follow the
   same switch as every other colour in the app: dark by default, light when
   the OS asks and nothing overrides it, light when the app is explicitly set
   to it.

   The FOURTH block is the one that is not about the theme. A picker tile is
   filled with --carbon-surface2 and lights up under the pointer, and in the
   dark theme it lights up all the way to white - so for as long as the pointer
   is on it, a dark-theme mark is standing on a LIGHT ground and has to wear
   its light value. Without this, twelve marks measured 1.00 against the tile
   they were sitting on: put.io, OpenCloud, Cloudinary, the Internet Archive
   and the rest went from white-on-charcoal to white-on-white the moment
   somebody pointed at them, which is the one place a list of logos must not
   go blank. The class marks the tiles that do it; a mark on any other surface
   is untouched.
*/
"""

# The class a control wears when its hover goes light. Named for what it does
# to the ground rather than for where it is used, because the rule is about the
# surface: anything that lights up this far owes its marks the switch.
HOVER_LIGHT_CLASS = "brand-hover-light"


def css_block(selectors, index, indent=0):
    """One rule: its selectors, one custom property per mark, closing brace."""
    pad = " " * indent
    lines = ["%s%s," % (pad, s) for s in selectors[:-1]]
    lines.append("%s%s {" % (pad, selectors[-1]))
    for name, on_dark, on_light in VARIABLES:
        lines.append("%s  %s: %s;" % (pad, name, on_dark if index == 1 else on_light))
    lines.append("%s}" % pad)
    return "\n".join(lines)


bekannt = {m[0] for m in MARKS} | {m[0] for m in LOCAL}
unbenutzt = sorted(set(INK) - bekannt)
if unbenutzt:
    raise SystemExit("INK names marks that do not exist: " + ", ".join(unbenutzt))

if not SRC.is_dir():
    raise SystemExit("no such directory: %s\nInstall simple-icons and pass its icons path." % SRC)

components = [one(*m) for m in MARKS] + [local(*m) for m in LOCAL]
# Cropping runs LAST, over the finished markup, so it sees the same drawing the
# app does: plate dropped, styles folded in, colours swapped for variables.
components = [crop_to_ink(c, m[0]) for c, m in zip(components, MARKS + LOCAL)]
if REDUNDANT:
    raise SystemExit(
        "These INK overrides only restate what the measurement already found. "
        "Delete them:\n" + "\n".join(
            "  %s: %r (measured %r)" % row for row in REDUNDANT
        )
    )
parts = [HEAD] + components
io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(parts))

css = [CSS_HEAD]
if VARIABLES:
    css.append(css_block([":root", '[data-theme="dark"]'], 1))
    css.append(
        "@media (prefers-color-scheme: light) {\n"
        + css_block([':root:not([data-theme="dark"])'], 2, indent=2)
        + "\n}"
    )
    css.append(css_block(['[data-theme="light"]'], 2))
    # Only the dark theme needs it. The light theme's hover moves to
    # --carbon-surface3, which is still a light ground, and the light values
    # already clear the floor against it - that is what GROUNDS_LIGHT is for.
    css.append(css_block(['[data-theme="dark"] .%s:hover' % HOVER_LIGHT_CLASS], 2))
io.open(CSS_OUT, "w", encoding="utf-8", newline="\n").write("\n\n".join(css) + "\n")

flipped = sorted({name.rsplit("-", 1)[0][8:] for name, _, _ in VARIABLES})
print("%s: %d marks (%d from Simple Icons, %d local)" % (OUT.name, len(MARKS) + len(LOCAL), len(MARKS), len(LOCAL)))
print("%s: %d variables for %d marks (%s)" % (CSS_OUT.name, len(VARIABLES), len(flipped), ", ".join(flipped)))
