# -*- coding: utf-8 -*-
"""Schreibt src/locales.ts aus den Sprachdateien in web/src/lib/locales.

Die Weboberflaeche laedt ihre Sprachen mit `import.meta.glob`, das Metro nicht
kennt, also muessen die Importe einzeln dastehen. Die erzeugte Datei wird
eingecheckt und nicht beim Bauen geschrieben.
"""
import io
import os

HIER = os.path.dirname(os.path.abspath(__file__))
QUELLE = os.path.normpath(os.path.join(HIER, "..", "..", "web", "src", "lib", "locales"))
ZIEL = os.path.normpath(os.path.join(HIER, "..", "src", "locales.ts"))

# Namen, die in JavaScript reserviert sind und als Bezeichner nicht gehen.
# `in` ist Hindi, und ohne diese Liste erzeugt das eine Datei, die nicht parst.
RESERVIERT = {"in", "do", "if", "for", "new", "var", "let", "const", "class"}

KOPF = '''// Every language is bundled, so a translation never has to be fetched offline.
// Generated by tools/make_locales.py from the files in web/src/lib/locales.

import type { Translations } from "../../web/src/lib/i18n.data";
'''


def bezeichner(code):
    return "x_" + code if code in RESERVIERT else code


def main():
    codes = sorted(f[:-3] for f in os.listdir(QUELLE) if f.endswith(".ts"))
    if not codes:
        raise SystemExit("keine Sprachdateien unter %s" % QUELLE)

    importe = "\n".join(
        'import %s from "../../web/src/lib/locales/%s";' % (bezeichner(c), c) for c in codes
    )
    tabelle = ",\n".join(
        '  "%s": %s as Partial<Translations>' % (c, bezeichner(c)) for c in codes
    )
    io.open(ZIEL, "w", encoding="utf-8", newline="\n").write(
        KOPF
        + "\n"
        + importe
        + "\n\nexport const locales: Record<string, Partial<Translations>> = {\n"
        + tabelle
        + ",\n};\n"
    )
    print("%d Sprachen nach %s geschrieben" % (len(codes), os.path.basename(ZIEL)))


if __name__ == "__main__":
    main()
