# -*- coding: utf-8 -*-
"""Schreibt src/locales.ts aus dem, was in web/src/lib/locales liegt.

EINE Uebersetzungsquelle, nicht zwei. Der Container und die App zeigen
dieselben Saetze, weil sie dieselben Dateien lesen - eine zweite Tabelle waere
dieselbe Arbeit ein zweites Mal und wuerde beim ersten Nachtrag auseinander
laufen, ohne dass es jemand meldet.

Warum ueberhaupt eine erzeugte Datei: die Weboberflaeche laedt ihre Sprachen
mit `import.meta.glob`, das Vite zur Bauzeit aufloest. Metro kennt das nicht
und kann ein Muster nicht aufloesen, also muessen die vierzig Importe
dastehen. Von Hand waere das eine Liste, die beim naechsten Sprachzusatz
vergessen wird; erzeugt ist sie es nicht.

Nach dem Lauf gehoert die Datei ins Repo. Sie wird nicht beim Bauen erzeugt,
weil ein Bau, der Quelltext schreibt, ein Bau ist, dessen Ergebnis niemand
gelesen hat.
"""
import io
import os

HIER = os.path.dirname(os.path.abspath(__file__))
QUELLE = os.path.normpath(os.path.join(HIER, "..", "..", "web", "src", "lib", "locales"))
ZIEL = os.path.normpath(os.path.join(HIER, "..", "src", "locales.ts"))

# Namen, die in JavaScript reserviert sind und als Bezeichner nicht gehen.
# `in` ist Hindi, und ohne diese Liste erzeugt das eine Datei, die nicht parst.
RESERVIERT = {"in", "do", "if", "for", "new", "var", "let", "const", "class"}

KOPF = '''// Every language, bundled.
//
// The web app fetches these one chunk at a time, because forty-one languages
// nobody is reading have no business in a page load. A phone is the opposite
// case: the download happened once at install, and a translation that has to
// be fetched is one that is missing on a train. So all of them are in here.
//
// Generated by tools/make_locales.py from web/src/lib/locales - the SAME files
// the container serves, so the two can never disagree about a sentence.

import type { Translations } from "../../web/src/lib/i18n.data";
'''


def bezeichner(code):
    return "x_" + code if code in RESERVIERT else code


def main():
    codes = sorted(f[:-3] for f in os.listdir(QUELLE) if f.endswith(".ts"))
    if not codes:
        raise SystemExit("keine Sprachdateien unter %s" % QUELLE)

    importe = "\n".join(
        'import %s from "../../web/src/lib/locales/%s";' % (bezeichner(c), c) for c in codes
    )
    tabelle = ",\n".join(
        '  "%s": %s as Partial<Translations>' % (c, bezeichner(c)) for c in codes
    )
    io.open(ZIEL, "w", encoding="utf-8", newline="\n").write(
        KOPF
        + "\n"
        + importe
        + "\n\nexport const locales: Record<string, Partial<Translations>> = {\n"
        + tabelle
        + ",\n};\n"
    )
    print("%d Sprachen nach %s geschrieben" % (len(codes), os.path.basename(ZIEL)))


if __name__ == "__main__":
    main()
